<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>19&nbsp; Classification using Trees and Rules – Tidymodels Computing Supplement</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/cls-neural-nets.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cca14224007e87b3f770119fd179b404.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span id="sec-cls-trees" class="quarto-section-identifier"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Classification using Trees and Rules</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../"></a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/aml4td/computing-tidymodels/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/news.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">News</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/contributing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributing</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/whole-game.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Whole Game</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Preparation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/initial-data-splitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Initial Data Splitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/numeric-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transforming Numeric Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/categorical-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with Categorical Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Embeddings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/interactions-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interactions and Nonlinear Features</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Optmization</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/overfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Overfitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measuring Performance with Resampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/grid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Grid Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/iterative-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Iterative Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/feature-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Feature Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/comparing-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparing Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Classification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/cls-metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Characterizing Classification Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/cls-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Generalized Linear and Additive Classifiers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/cls-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Complex Nonlinear Boundaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/cls-neural-nets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Neural Network Classifiers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/cls-trees.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Classification using Trees and Rules</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regression</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Characterization</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Finalization</span></span>
  </li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#requirements" id="toc-requirements" class="nav-link active" data-scroll-target="#requirements"><span class="header-section-number">19.1</span> Requirements</a></li>
  <li>
<a href="#sec-cls-tree-models" id="toc-sec-cls-tree-models" class="nav-link" data-scroll-target="#sec-cls-tree-models"><span class="header-section-number">19.2</span> Specific Tree-Based Models</a>
  <ul class="collapse">
<li><a href="#sec-cls-cart" id="toc-sec-cls-cart" class="nav-link" data-scroll-target="#sec-cls-cart"><span class="header-section-number">19.2.1</span> CART</a></li>
  <li><a href="#sec-cls-c50" id="toc-sec-cls-c50" class="nav-link" data-scroll-target="#sec-cls-c50"><span class="header-section-number">19.2.2</span> C4.5 and C5.0</a></li>
  <li><a href="#sec-cls-cit" id="toc-sec-cls-cit" class="nav-link" data-scroll-target="#sec-cls-cit"><span class="header-section-number">19.2.3</span> Conditional Inference Trees</a></li>
  <li><a href="#sec-cls-tree-global" id="toc-sec-cls-tree-global" class="nav-link" data-scroll-target="#sec-cls-tree-global"><span class="header-section-number">19.2.4</span> Globally Estimated Trees</a></li>
  <li><a href="#sec-cls-oblique" id="toc-sec-cls-oblique" class="nav-link" data-scroll-target="#sec-cls-oblique"><span class="header-section-number">19.2.5</span> Oblique Trees</a></li>
  </ul>
</li>
  <li><a href="#sec-cls-rules" id="toc-sec-cls-rules" class="nav-link" data-scroll-target="#sec-cls-rules"><span class="header-section-number">19.3</span> Rule-Based Models</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block"><span id="sec-cls-trees" class="quarto-section-identifier"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Classification using Trees and Rules</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In this chapter, we’ll describe the R packages for fitting different types of classification trees, along with their tidymodels interfaces.</p>
<p>We’ll skip several sections of the main text and go straight to the section on specific models. Many of the interfaces for low-level details, such as pruning or handling missing data, are internal to the R functions used to fit the models.</p>
<section id="requirements" class="level2" data-number="19.1"><h2 data-number="19.1" class="anchored" data-anchor-id="requirements">
<span class="header-section-number">19.1</span> Requirements</h2>
<p>You’ll need 8 packages (<span class="pkg"><a href="https://cran.r-project.org/package=aorsf">aorsf</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=bonsai">bonsai</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=evtree">evtree</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=rpart">rpart</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=rules">rules</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=spatialsample">spatialsample</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=tidymodels">tidymodels</a></span>) for this chapter:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># fmt: skip</span></span>
<span><span class="va">req_pkg</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"aorsf"</span>, <span class="st">"bonsai"</span>, <span class="st">"evtree"</span>, <span class="st">"partykit"</span>, <span class="st">"rpart"</span>, <span class="st">"rules"</span>,</span>
<span>    <span class="st">"spatialsample"</span>, <span class="st">"tidymodels"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check to see if they are installed:</span></span>
<span><span class="va">pkg_installed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">req_pkg</span>, <span class="fu">rlang</span><span class="fu">::</span><span class="va"><a href="https://rlang.r-lib.org/reference/is_installed.html">is_installed</a></span>, <span class="fu"><a href="https://rdrr.io/r/base/logical.html">logical</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Install missing packages:</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/any.html">any</a></span><span class="op">(</span><span class="op">!</span><span class="va">pkg_installed</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">install_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">pkg_installed</span><span class="op">)</span><span class="op">[</span><span class="op">!</span><span class="va">pkg_installed</span><span class="op">]</span></span>
<span>  <span class="fu">pak</span><span class="fu">::</span><span class="fu"><a href="https://pak.r-lib.org/reference/pak.html">pak</a></span><span class="op">(</span><span class="va">install_list</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s load the meta package and manage some between-package function conflicts.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/spatialsample">spatialsample</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://bonsai.tidymodels.org/">bonsai</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/rules">rules</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/probably">probably</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mirai.r-lib.org">mirai</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://tidymodels.tidymodels.org/reference/tidymodels_prefer.html">tidymodels_prefer</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">theme_set</span><span class="op">(</span><span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"top"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://mirai.r-lib.org/reference/daemons.html">daemons</a></span><span class="op">(</span><span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/detectCores.html">detectCores</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Some general settings for tuning classification models:</span></span>
<span><span class="va">cls_mtr</span> <span class="op">&lt;-</span> <span class="fu">metric_set</span><span class="op">(</span><span class="va">brier_class</span>, <span class="va">roc_auc</span>, <span class="va">pr_auc</span>, <span class="va">mn_log_loss</span><span class="op">)</span></span>
<span><span class="va">ctrl_grid</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">control_grid</span><span class="op">(</span></span>
<span>    save_pred <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    save_workflow <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    parallel_over <span class="op">=</span> <span class="st">"everything"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As before, we’ll load the objects that were already computed for the forestation data:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="st">"https://raw.githubusercontent.com/aml4td/website/main/RData/forested_data.RData"</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/connections.html">url</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="sec-cls-tree-models" class="level2" data-number="19.2"><h2 data-number="19.2" class="anchored" data-anchor-id="sec-cls-tree-models">
<span class="header-section-number">19.2</span> Specific Tree-Based Models</h2>
<p>Let’s look at how to fit the four main types of decision trees described in the text.</p>
<section id="sec-cls-cart" class="level3" data-number="19.2.1"><h3 data-number="19.2.1" class="anchored" data-anchor-id="sec-cls-cart">
<span class="header-section-number">19.2.1</span> CART</h3>
<p>The CART model is accessible using the <span class="pkg"><a href="https://cran.r-project.org/package=rpart">rpart</a></span> package. By default, it uses cost-complexity pruning, surrogate splits, and a one-standard error rule. There are arguments to supersede the defaults.</p>
<p>If you use the package directly, <code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart::rpart()</a></code> has only a formula method and does not automatically convert categorical predictors to indicator columns. For example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bethatkinson/rpart">rpart</a></span><span class="op">)</span></span>
<span><span class="va">cart_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">county</span> <span class="op">+</span> <span class="va">elevation</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">cart_fit</span></span>
<span><span class="co">#&gt; n= 4832 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; node), split, n, loss, yval, (yprob)</span></span>
<span><span class="co">#&gt;       * denotes terminal node</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  1) root 4832 2118 Yes (0.56167 0.43833)  </span></span>
<span><span class="co">#&gt;    2) county=chelan,clallam,clark,cowlitz,ferry,grays_harbor,jefferson,king,kitsap,kittitas,klickitat,lewis,mason,okanogan,pacific,pend_oreille,pierce,san_juan,skagit,skamania,snohomish,spokane,stevens,thurston,wahkiakum,whatcom 3276  767 Yes (0.76587 0.23413)  </span></span>
<span><span class="co">#&gt;      4) county=clallam,cowlitz,ferry,grays_harbor,jefferson,kitsap,lewis,mason,pacific,pend_oreille,san_juan,skamania,snohomish,stevens,wahkiakum 1675  183 Yes (0.89075 0.10925) *</span></span>
<span><span class="co">#&gt;      5) county=chelan,clark,king,kittitas,klickitat,okanogan,pierce,skagit,spokane,thurston,whatcom 1601  584 Yes (0.63523 0.36477)  </span></span>
<span><span class="co">#&gt;       10) elevation&gt;=823 718  138 Yes (0.80780 0.19220) *</span></span>
<span><span class="co">#&gt;       11) elevation&lt; 823 883  437 No (0.49490 0.50510)  </span></span>
<span><span class="co">#&gt;         22) county=chelan,clark,king,pierce,skagit,thurston,whatcom 517  191 Yes (0.63056 0.36944)  </span></span>
<span><span class="co">#&gt;           44) elevation&gt;=93 370   82 Yes (0.77838 0.22162) *</span></span>
<span><span class="co">#&gt;           45) elevation&lt; 93 147   38 No (0.25850 0.74150) *</span></span>
<span><span class="co">#&gt;         23) county=kittitas,klickitat,okanogan,spokane 366  111 No (0.30328 0.69672) *</span></span>
<span><span class="co">#&gt;    3) county=adams,asotin,benton,columbia,douglas,franklin,garfield,grant,island,lincoln,walla_walla,whitman,yakima 1556  205 No (0.13175 0.86825)  </span></span>
<span><span class="co">#&gt;      6) elevation&gt;=929.5 196   40 Yes (0.79592 0.20408) *</span></span>
<span><span class="co">#&gt;      7) elevation&lt; 929.5 1360   49 No (0.03603 0.96397) *</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The terminal nodes show up in the output where the right-hand side has an asterisk. For example, this output:</p>
<pre><code>        718  138 Yes (0.80780 0.19220) *</code></pre>
<p>for a terminal node where the first level of the factor (“Yes” in this case) had 718 data points, and the other level had 138. The relative proportions of those frequencies are in parentheses.</p>
<p>The package has a number of S3 methods that are helpful. Along with the standard <code><a href="https://rdrr.io/r/base/print.html">print()</a></code> and <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> methods, there is also a <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> method that visualizes the splits. However, the <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span> package has a better plotting mechanism. To use it, first use <code><a href="https://rdrr.io/pkg/partykit/man/party-coercion.html">partykit::as.party()</a></code> to convert the object’s format, then use <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>.</p>
<p>Another function that is helpful that can extract the rule to a terminal node is:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/rpart/man/path.rpart.html">path.rpart</a></span><span class="op">(</span><span class="va">cart_fit</span>, <span class="fl">11</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  node number: 11 </span></span>
<span><span class="co">#&gt;    root</span></span>
<span><span class="co">#&gt;    county=chelan,clallam,clark,cowlitz,ferry,grays_harbor,jefferson,king,kitsap,kittitas,klickitat,lewis,mason,okanogan,pacific,pend_oreille,pierce,san_juan,skagit,skamania,snohomish,spokane,stevens,thurston,wahkiakum,whatcom</span></span>
<span><span class="co">#&gt;    county=chelan,clark,king,kittitas,klickitat,okanogan,pierce,skagit,spokane,thurston,whatcom</span></span>
<span><span class="co">#&gt;    elevation&lt; 823</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/pkg/rpart/man/rpart.control.html">rpart.control()</a></code> function specifies how the model is trained. Any arguments that are passed to this function could also have been passed directly to <code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart()</a></code> itself. For example, we can control how many (or any) surrogate splits are determined when training. For example, to avoid surrogate splits (and use the whole predictor set):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">no_surrogate_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart</a></span><span class="op">(</span></span>
<span>  <span class="va">class</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>  data <span class="op">=</span> <span class="va">forested_train</span>,</span>
<span>  usesurrogate <span class="op">=</span> <span class="fl">0</span>,</span>
<span>  maxsurrogate <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span>
<span><span class="va">no_surrogate_fit</span></span>
<span><span class="co">#&gt; n= 4832 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; node), split, n, loss, yval, (yprob)</span></span>
<span><span class="co">#&gt;       * denotes terminal node</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  1) root 4832 2118 Yes (0.56167 0.43833)  </span></span>
<span><span class="co">#&gt;    2) vapor_max&lt; 1248 2952  515 Yes (0.82554 0.17446)  </span></span>
<span><span class="co">#&gt;      4) roughness&gt;=12.5 2491  301 Yes (0.87916 0.12084)  </span></span>
<span><span class="co">#&gt;        8) temp_annual_max&gt;=6.675 2391  239 Yes (0.90004 0.09996) *</span></span>
<span><span class="co">#&gt;        9) temp_annual_max&lt; 6.675 100   38 No (0.38000 0.62000)  </span></span>
<span><span class="co">#&gt;         18) longitude&gt;=-120.6 32    5 Yes (0.84375 0.15625) *</span></span>
<span><span class="co">#&gt;         19) longitude&lt; -120.6 68   11 No (0.16176 0.83824) *</span></span>
<span><span class="co">#&gt;      5) roughness&lt; 12.5 461  214 Yes (0.53579 0.46421)  </span></span>
<span><span class="co">#&gt;       10) county=clallam,grays_harbor,jefferson,kitsap,klickitat,mason,okanogan,pacific,pend_oreille,skamania,yakima 192   31 Yes (0.83854 0.16146) *</span></span>
<span><span class="co">#&gt;       11) county=asotin,chelan,clark,columbia,cowlitz,douglas,garfield,island,king,kittitas,lewis,lincoln,pierce,san_juan,skagit,snohomish,spokane,stevens,thurston,wahkiakum,whatcom 269   86 No (0.31970 0.68030) *</span></span>
<span><span class="co">#&gt;    3) vapor_max&gt;=1248 1880  277 No (0.14734 0.85266)  </span></span>
<span><span class="co">#&gt;      6) county=chelan,ferry,klickitat,okanogan,pend_oreille,spokane,stevens 521  253 No (0.48560 0.51440)  </span></span>
<span><span class="co">#&gt;       12) precip_annual&gt;=358.5 391  157 Yes (0.59847 0.40153)  </span></span>
<span><span class="co">#&gt;         24) latitude&gt;=47.76 253   69 Yes (0.72727 0.27273) *</span></span>
<span><span class="co">#&gt;         25) latitude&lt; 47.76 138   50 No (0.36232 0.63768) *</span></span>
<span><span class="co">#&gt;       13) precip_annual&lt; 358.5 130   19 No (0.14615 0.85385) *</span></span>
<span><span class="co">#&gt;      7) county=adams,asotin,benton,columbia,douglas,franklin,garfield,grant,kittitas,lincoln,walla_walla,whitman,yakima 1359   24 No (0.01766 0.98234) *</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that this did not affect the true splits.</p>
<p>The model has an internal variable importance score. Let’s</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">no_surrogate_fit</span><span class="op">$</span><span class="va">variable.importance</span></span>
<span><span class="co">#&gt;       vapor_max          county       roughness temp_annual_max   precip_annual </span></span>
<span><span class="co">#&gt;         1056.56          225.26           91.73           51.92           39.92 </span></span>
<span><span class="co">#&gt;        latitude       longitude </span></span>
<span><span class="co">#&gt;           23.79           20.24</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A few points about this:</p>
<ul>
<li>This does not list the entire predictor set, only those that had at least one split.</li>
<li>
<em>By default</em>, the importance scores will include the effects of surrogate or competing splits. These may be at odds with what you would have seen with other types of splits.</li>
</ul>
<p>Using tidymodels, <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span> is the default engine for <code><a href="https://parsnip.tidymodels.org/reference/decision_tree.html">decision_tree()</a></code>. Since it can fit both classification and regression models, we will need to set the model mode. For example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="va">cart_fit</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/decision_tree.html">decision_tree</a></span><span class="op">(</span>cost_complexity <span class="op">=</span> <span class="fl">0.001</span>, min_n <span class="op">=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_args.html">set_mode</a></span><span class="op">(</span><span class="st">"classification"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">cart_fit</span></span>
<span><span class="co">#&gt; parsnip model object</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; n= 4832 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; node), split, n, loss, yval, (yprob)</span></span>
<span><span class="co">#&gt;       * denotes terminal node</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   1) root 4832 2118 Yes (0.56167 0.43833)  </span></span>
<span><span class="co">#&gt;     2) vapor_max&lt; 1248 2952  515 Yes (0.82554 0.17446)  </span></span>
<span><span class="co">#&gt;       4) roughness&gt;=12.5 2491  301 Yes (0.87916 0.12084)  </span></span>
<span><span class="co">#&gt;         8) temp_annual_max&gt;=6.675 2391  239 Yes (0.90004 0.09996)  </span></span>
<span><span class="co">#&gt;          16) county=chelan,clallam,columbia,cowlitz,ferry,garfield,grays_harbor,jefferson,king,kitsap,kittitas,klickitat,lewis,mason,okanogan,pacific,pend_oreille,pierce,san_juan,skagit,skamania,snohomish,spokane,stevens,thurston,wahkiakum,walla_walla,whatcom,yakima 2302  194 Yes (0.91573 0.08427)  </span></span>
<span><span class="co">#&gt;            32) temp_annual_mean&lt; 11.09 2267  174 Yes (0.92325 0.07675)  </span></span>
<span><span class="co">#&gt;              64) precip_annual&gt;=461.5 2184  142 Yes (0.93498 0.06502) *</span></span>
<span><span class="co">#&gt;              65) precip_annual&lt; 461.5 83   32 Yes (0.61446 0.38554)  </span></span>
<span><span class="co">#&gt;               130) county=ferry,okanogan 64   14 Yes (0.78125 0.21875) *</span></span>
<span><span class="co">#&gt;               131) county=chelan,kittitas,klickitat,spokane,yakima 19    1 No (0.05263 0.94737) *</span></span>
<span><span class="co">#&gt;            33) temp_annual_mean&gt;=11.09 35   15 No (0.42857 0.57143) *</span></span>
<span><span class="co">#&gt;          17) county=asotin,clark,douglas,island,lincoln,whitman 89   44 No (0.49438 0.50562)  </span></span>
<span><span class="co">#&gt;            34) precip_annual&gt;=1938 18    0 Yes (1.00000 0.00000) *</span></span>
<span><span class="co">#&gt;            35) precip_annual&lt; 1938 71   26 No (0.36620 0.63380)  </span></span>
<span><span class="co">#&gt;              70) roughness&gt;=30.5 29   11 Yes (0.62069 0.37931) *</span></span>
<span><span class="co">#&gt;              71) roughness&lt; 30.5 42    8 No (0.19048 0.80952) *</span></span>
<span><span class="co">#&gt;         9) temp_annual_max&lt; 6.675 100   38 No (0.38000 0.62000)  </span></span>
<span><span class="co">#&gt;          18) longitude&gt;=-120.6 32    5 Yes (0.84375 0.15625) *</span></span>
<span><span class="co">#&gt;          19) longitude&lt; -120.6 68   11 No (0.16176 0.83824) *</span></span>
<span><span class="co">#&gt;       5) roughness&lt; 12.5 461  214 Yes (0.53579 0.46421)  </span></span>
<span><span class="co">#&gt;        10) county=clallam,grays_harbor,jefferson,kitsap,klickitat,mason,okanogan,pacific,pend_oreille,skamania,yakima 192   31 Yes (0.83854 0.16146)  </span></span>
<span><span class="co">#&gt;          20) temp_annual_mean&lt; 10.77 173   18 Yes (0.89595 0.10405) *</span></span>
<span><span class="co">#&gt;          21) temp_annual_mean&gt;=10.77 19    6 No (0.31579 0.68421) *</span></span>
<span><span class="co">#&gt;        11) county=asotin,chelan,clark,columbia,cowlitz,douglas,garfield,island,king,kittitas,lewis,lincoln,pierce,san_juan,skagit,snohomish,spokane,stevens,thurston,wahkiakum,whatcom 269   86 No (0.31970 0.68030)  </span></span>
<span><span class="co">#&gt;          22) precip_annual&gt;=1395 61   25 Yes (0.59016 0.40984)  </span></span>
<span><span class="co">#&gt;            44) county=chelan,king,lewis,pierce,skagit,snohomish 37    9 Yes (0.75676 0.24324) *</span></span>
<span><span class="co">#&gt;            45) county=clark,cowlitz,thurston,wahkiakum,whatcom 24    8 No (0.33333 0.66667) *</span></span>
<span><span class="co">#&gt;          23) precip_annual&lt; 1395 208   50 No (0.24038 0.75962) *</span></span>
<span><span class="co">#&gt;     3) vapor_max&gt;=1248 1880  277 No (0.14734 0.85266)  </span></span>
<span><span class="co">#&gt;       6) county=chelan,ferry,klickitat,okanogan,pend_oreille,spokane,stevens 521  253 No (0.48560 0.51440)  </span></span>
<span><span class="co">#&gt;        12) precip_annual&gt;=358.5 391  157 Yes (0.59847 0.40153)  </span></span>
<span><span class="co">#&gt;          24) latitude&gt;=47.76 253   69 Yes (0.72727 0.27273)  </span></span>
<span><span class="co">#&gt;            48) roughness&gt;=8.5 201   44 Yes (0.78109 0.21891)  </span></span>
<span><span class="co">#&gt;              96) latitude&lt; 48.3 137   17 Yes (0.87591 0.12409) *</span></span>
<span><span class="co">#&gt;              97) latitude&gt;=48.3 64   27 Yes (0.57812 0.42188)  </span></span>
<span><span class="co">#&gt;               194) northness&gt;=-53.5 47   16 Yes (0.65957 0.34043) *</span></span>
<span><span class="co">#&gt;               195) northness&lt; -53.5 17    6 No (0.35294 0.64706) *</span></span>
<span><span class="co">#&gt;            49) roughness&lt; 8.5 52   25 Yes (0.51923 0.48077)  </span></span>
<span><span class="co">#&gt;              98) temp_annual_max&lt; 15.1 34   13 Yes (0.61765 0.38235) *</span></span>
<span><span class="co">#&gt;              99) temp_annual_max&gt;=15.1 18    6 No (0.33333 0.66667) *</span></span>
<span><span class="co">#&gt;          25) latitude&lt; 47.76 138   50 No (0.36232 0.63768)  </span></span>
<span><span class="co">#&gt;            50) precip_annual&gt;=593 23    5 Yes (0.78261 0.21739) *</span></span>
<span><span class="co">#&gt;            51) precip_annual&lt; 593 115   32 No (0.27826 0.72174) *</span></span>
<span><span class="co">#&gt;        13) precip_annual&lt; 358.5 130   19 No (0.14615 0.85385)  </span></span>
<span><span class="co">#&gt;          26) county=ferry 17    7 Yes (0.58824 0.41176) *</span></span>
<span><span class="co">#&gt;          27) county=chelan,klickitat,okanogan 113    9 No (0.07965 0.92035) *</span></span>
<span><span class="co">#&gt;       7) county=adams,asotin,benton,columbia,douglas,franklin,garfield,grant,kittitas,lincoln,walla_walla,whitman,yakima 1359   24 No (0.01766 0.98234) *</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>There <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> and <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> methods have predictable results:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">cart_fit</span>, <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">forested_test</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 1</span></span>
<span><span class="co">#&gt;   .pred_class</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;      </span></span>
<span><span class="co">#&gt; 1 No         </span></span>
<span><span class="co">#&gt; 2 No         </span></span>
<span><span class="co">#&gt; 3 No         </span></span>
<span><span class="co">#&gt; 4 Yes        </span></span>
<span><span class="co">#&gt; 5 No         </span></span>
<span><span class="co">#&gt; 6 Yes</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">cart_fit</span>, <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">forested_test</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 20</span></span>
<span><span class="co">#&gt;   .pred_class .pred_Yes .pred_No class  year elevation eastness northness roughness</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;           &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 No            0.01766  0.9823  No     2014       308      -70       -70         4</span></span>
<span><span class="co">#&gt; 2 No            0.01766  0.9823  No     2014       119       94        31         2</span></span>
<span><span class="co">#&gt; 3 No            0.01766  0.9823  No     2014       795      -74        66        39</span></span>
<span><span class="co">#&gt; 4 Yes           0.9350   0.06502 Yes    2014      1825       99        -9        78</span></span>
<span><span class="co">#&gt; 5 No            0.07965  0.9204  No     2014       126       83       -55         6</span></span>
<span><span class="co">#&gt; 6 Yes           0.9350   0.06502 Yes    2014      1056       99         7        57</span></span>
<span><span class="co">#&gt; # ℹ 11 more variables: dew_temp &lt;dbl&gt;, precip_annual &lt;dbl&gt;, temp_annual_mean &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   temp_annual_min &lt;dbl&gt;, temp_annual_max &lt;dbl&gt;, temp_january_min &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   vapor_min &lt;dbl&gt;, vapor_max &lt;dbl&gt;, county &lt;fct&gt;, longitude &lt;dbl&gt;, latitude &lt;dbl&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><a href="https://aml4td.org/chapters/cls-trees.html#sec-cls-cart"><i class="fa-solid fa-rotate-left fa-small" aria-label="rotate-left"></i></a></p>
</section><section id="sec-cls-c50" class="level3" data-number="19.2.2"><h3 data-number="19.2.2" class="anchored" data-anchor-id="sec-cls-c50">
<span class="header-section-number">19.2.2</span> C4.5 and C5.0</h3>
<p>There is no native R reference implementation for C4.5, although a Java-based implementation is available via <code>RWeka::J48()</code>.</p>
<p>C5.0 trees and rules are available in the <span class="pkg"><a href="https://cran.r-project.org/package=C50">C50</a></span> package. There are x/y interfaces as well as one that takes a formula. There is also a <code><a href="https://topepo.github.io/C5.0/reference/C5.0Control.html">C5.0Control()</a></code> function that controls details related to growing and pruning trees.</p>
<p>An example usage is:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://topepo.github.io/C5.0/">C50</a></span><span class="op">)</span></span>
<span><span class="va">c5_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://topepo.github.io/C5.0/reference/C5.0.html">C5.0</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">c5_fit</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; C5.0.formula(formula = class ~ ., data = forested_train)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Classification Tree</span></span>
<span><span class="co">#&gt; Number of samples: 4832 </span></span>
<span><span class="co">#&gt; Number of predictors: 16 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Tree size: 50 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Non-standard options: attempt to group attributes</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If you want to see the actual tree, use the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> method:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">c5_fit</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; C5.0.formula(formula = class ~ ., data = forested_train)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; C5.0 [Release 2.07 GPL Edition]      Fri May 22 12:49:33 2026</span></span>
<span><span class="co">#&gt; -------------------------------</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Class specified by attribute `outcome'</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Read 4832 cases (17 attributes) from undefined.data</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Decision tree:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; county in {adams,benton,douglas,franklin,grant,lincoln,walla_walla,</span></span>
<span><span class="co">#&gt; :          whitman}: No (1056/14)</span></span>
<span><span class="co">#&gt; county in {asotin,chelan,clallam,clark,columbia,cowlitz,ferry,garfield,</span></span>
<span><span class="co">#&gt; :          grays_harbor,island,jefferson,king,kitsap,kittitas,klickitat,lewis,</span></span>
<span><span class="co">#&gt; :          mason,okanogan,pacific,pend_oreille,pierce,san_juan,skagit,skamania,</span></span>
<span><span class="co">#&gt; :          snohomish,spokane,stevens,thurston,wahkiakum,whatcom,yakima}:</span></span>
<span><span class="co">#&gt; :...precip_annual &lt;= 464:</span></span>
<span><span class="co">#&gt;     :...temp_annual_mean &gt; 7.8:</span></span>
<span><span class="co">#&gt;     :   :...county in {clark,cowlitz,grays_harbor,island,jefferson,king,kitsap,</span></span>
<span><span class="co">#&gt;     :   :   :          lewis,mason,pacific,pend_oreille,pierce,san_juan,skagit,</span></span>
<span><span class="co">#&gt;     :   :   :          skamania,snohomish,thurston,wahkiakum,</span></span>
<span><span class="co">#&gt;     :   :   :          whatcom}: No (0)</span></span>
<span><span class="co">#&gt;     :   :   county in {clallam,ferry,stevens}: Yes (55/17)</span></span>
<span><span class="co">#&gt;     :   :   county in {asotin,chelan,columbia,garfield,kittitas,klickitat,</span></span>
<span><span class="co">#&gt;     :   :   :          okanogan,spokane,yakima}:</span></span>
<span><span class="co">#&gt;     :   :   :...dew_temp &gt; 0.03: No (484/39)</span></span>
<span><span class="co">#&gt;     :   :       dew_temp &lt;= 0.03:</span></span>
<span><span class="co">#&gt;     :   :       :...longitude &lt;= -119.4271: Yes (28/11)</span></span>
<span><span class="co">#&gt;     :   :           longitude &gt; -119.4271: No (7)</span></span>
<span><span class="co">#&gt;     :   temp_annual_mean &lt;= 7.8:</span></span>
<span><span class="co">#&gt;     :   :...county in {chelan,kittitas}: No (3)</span></span>
<span><span class="co">#&gt;     :       county in {asotin,clallam,clark,columbia,cowlitz,ferry,garfield,</span></span>
<span><span class="co">#&gt;     :       :          grays_harbor,island,jefferson,king,kitsap,klickitat,</span></span>
<span><span class="co">#&gt;     :       :          lewis,mason,pacific,pend_oreille,pierce,san_juan,skagit,</span></span>
<span><span class="co">#&gt;     :       :          skamania,snohomish,spokane,stevens,thurston,wahkiakum,</span></span>
<span><span class="co">#&gt;     :       :          whatcom,yakima}: Yes (13)</span></span>
<span><span class="co">#&gt;     :       county = okanogan:</span></span>
<span><span class="co">#&gt;     :       :...latitude &lt;= 48.45825: Yes (17)</span></span>
<span><span class="co">#&gt;     :           latitude &gt; 48.45825:</span></span>
<span><span class="co">#&gt;     :           :...year &gt; 2013: Yes (34/8)</span></span>
<span><span class="co">#&gt;     :               year &lt;= 2013:</span></span>
<span><span class="co">#&gt;     :               :...eastness &lt;= -63: No (6)</span></span>
<span><span class="co">#&gt;     :                   eastness &gt; -63:</span></span>
<span><span class="co">#&gt;     :                   :...vapor_min &lt;= 205: Yes (9/2)</span></span>
<span><span class="co">#&gt;     :                       vapor_min &gt; 205: No (4)</span></span>
<span><span class="co">#&gt;     precip_annual &gt; 464:</span></span>
<span><span class="co">#&gt;     :...elevation &lt;= 32:</span></span>
<span><span class="co">#&gt;         :...precip_annual &lt;= 1910: No (107/18)</span></span>
<span><span class="co">#&gt;         :   precip_annual &gt; 1910:</span></span>
<span><span class="co">#&gt;         :   :...temp_annual_mean &lt;= 10.69: Yes (26/4)</span></span>
<span><span class="co">#&gt;         :       temp_annual_mean &gt; 10.69:</span></span>
<span><span class="co">#&gt;         :       :...dew_temp &lt;= 6.99: Yes (2)</span></span>
<span><span class="co">#&gt;         :           dew_temp &gt; 6.99: No (10/1)</span></span>
<span><span class="co">#&gt;         elevation &gt; 32:</span></span>
<span><span class="co">#&gt;         :...latitude &lt;= 45.73898:</span></span>
<span><span class="co">#&gt;             :...county in {asotin,chelan,clallam,clark,columbia,cowlitz,ferry,</span></span>
<span><span class="co">#&gt;             :   :          garfield,grays_harbor,island,jefferson,king,kitsap,</span></span>
<span><span class="co">#&gt;             :   :          kittitas,klickitat,lewis,mason,okanogan,pacific,</span></span>
<span><span class="co">#&gt;             :   :          pend_oreille,pierce,san_juan,skagit,snohomish,</span></span>
<span><span class="co">#&gt;             :   :          spokane,stevens,thurston,wahkiakum,whatcom,</span></span>
<span><span class="co">#&gt;             :   :          yakima}: No (22/3)</span></span>
<span><span class="co">#&gt;             :   county = skamania: Yes (4)</span></span>
<span><span class="co">#&gt;             latitude &gt; 45.73898:</span></span>
<span><span class="co">#&gt;             :...dew_temp &lt;= -4.05:</span></span>
<span><span class="co">#&gt;                 :...longitude &lt;= -120.5846: No (54/6)</span></span>
<span><span class="co">#&gt;                 :   longitude &gt; -120.5846: Yes (41/5)</span></span>
<span><span class="co">#&gt;                 dew_temp &gt; -4.05:</span></span>
<span><span class="co">#&gt;                 :...county in {asotin,clark,columbia,garfield,island,spokane,</span></span>
<span><span class="co">#&gt;                     :          thurston}:</span></span>
<span><span class="co">#&gt;                     :...precip_annual &gt; 630:</span></span>
<span><span class="co">#&gt;                     :   :...roughness &gt; 15: Yes (152/20)</span></span>
<span><span class="co">#&gt;                     :   :   roughness &lt;= 15:</span></span>
<span><span class="co">#&gt;                     :   :   :...year &lt;= 2010: Yes (6)</span></span>
<span><span class="co">#&gt;                     :   :       year &gt; 2010: No (41/14)</span></span>
<span><span class="co">#&gt;                     :   precip_annual &lt;= 630:</span></span>
<span><span class="co">#&gt;                     :   :...temp_january_min &gt; 3.78: No (51/1)</span></span>
<span><span class="co">#&gt;                     :       temp_january_min &lt;= 3.78:</span></span>
<span><span class="co">#&gt;                     :       :...vapor_min &gt; 232: Yes (11/1)</span></span>
<span><span class="co">#&gt;                     :           vapor_min &lt;= 232:</span></span>
<span><span class="co">#&gt;                     :           :...latitude &lt;= 47.53998: No (25/2)</span></span>
<span><span class="co">#&gt;                     :               latitude &gt; 47.53998:</span></span>
<span><span class="co">#&gt;                     :               :...roughness &lt;= 18: No (20/6)</span></span>
<span><span class="co">#&gt;                     :                   roughness &gt; 18: Yes (12/1)</span></span>
<span><span class="co">#&gt;                     county in {chelan,clallam,cowlitz,ferry,grays_harbor,</span></span>
<span><span class="co">#&gt;                     :          jefferson,king,kitsap,kittitas,klickitat,lewis,</span></span>
<span><span class="co">#&gt;                     :          mason,okanogan,pacific,pend_oreille,pierce,</span></span>
<span><span class="co">#&gt;                     :          san_juan,skagit,skamania,snohomish,stevens,</span></span>
<span><span class="co">#&gt;                     :          wahkiakum,whatcom,yakima}:</span></span>
<span><span class="co">#&gt;                     :...temp_annual_mean &gt; 10.62:</span></span>
<span><span class="co">#&gt;                         :...longitude &lt;= -122.5701:</span></span>
<span><span class="co">#&gt;                         :   :...temp_annual_max &lt;= 16.49: Yes (120/10)</span></span>
<span><span class="co">#&gt;                         :   :   temp_annual_max &gt; 16.49:</span></span>
<span><span class="co">#&gt;                         :   :   :...vapor_max &lt;= 1012: No (6/1)</span></span>
<span><span class="co">#&gt;                         :   :       vapor_max &gt; 1012: Yes (34/11)</span></span>
<span><span class="co">#&gt;                         :   longitude &gt; -122.5701:</span></span>
<span><span class="co">#&gt;                         :   :...roughness &gt; 45: Yes (13)</span></span>
<span><span class="co">#&gt;                         :       roughness &lt;= 45:</span></span>
<span><span class="co">#&gt;                         :       :...longitude &lt;= -122.0837: No (67/11)</span></span>
<span><span class="co">#&gt;                         :           longitude &gt; -122.0837:</span></span>
<span><span class="co">#&gt;                         :           :...roughness &lt;= 4: No (2)</span></span>
<span><span class="co">#&gt;                         :               roughness &gt; 4: Yes (10)</span></span>
<span><span class="co">#&gt;                         temp_annual_mean &lt;= 10.62:</span></span>
<span><span class="co">#&gt;                         :...temp_annual_max &lt;= 6.84:</span></span>
<span><span class="co">#&gt;                             :...year &lt;= 2007: Yes (3)</span></span>
<span><span class="co">#&gt;                             :   year &gt; 2007:</span></span>
<span><span class="co">#&gt;                             :   :...dew_temp &lt;= -3.88: Yes (4)</span></span>
<span><span class="co">#&gt;                             :       dew_temp &gt; -3.88: No (20/4)</span></span>
<span><span class="co">#&gt;                             temp_annual_max &gt; 6.84:</span></span>
<span><span class="co">#&gt;                             :...vapor_max &gt; 1201:</span></span>
<span><span class="co">#&gt;                                 :...temp_annual_max &lt;= 15: Yes (219/34)</span></span>
<span><span class="co">#&gt;                                 :   temp_annual_max &gt; 15:</span></span>
<span><span class="co">#&gt;                                 :   :...longitude &lt;= -120.6273: Yes (15/2)</span></span>
<span><span class="co">#&gt;                                 :       longitude &gt; -120.6273:</span></span>
<span><span class="co">#&gt;                                 :       :...temp_annual_min &lt;= -4.92: Yes (18/8)</span></span>
<span><span class="co">#&gt;                                 :           temp_annual_min &gt; -4.92: No (9)</span></span>
<span><span class="co">#&gt;                                 vapor_max &lt;= 1201:</span></span>
<span><span class="co">#&gt;                                 :...roughness &lt;= 4:</span></span>
<span><span class="co">#&gt;                                     :...longitude &lt;= -122.6583: Yes (26/1)</span></span>
<span><span class="co">#&gt;                                     :   longitude &gt; -122.6583:</span></span>
<span><span class="co">#&gt;                                     :   :...vapor_min &lt;= 106: No (25/9)</span></span>
<span><span class="co">#&gt;                                     :       vapor_min &gt; 106: Yes (5)</span></span>
<span><span class="co">#&gt;                                     roughness &gt; 4:</span></span>
<span><span class="co">#&gt;                                     :...roughness &lt;= 191: Yes (1893/82)</span></span>
<span><span class="co">#&gt;                                         roughness &gt; 191:</span></span>
<span><span class="co">#&gt;                                         :...temp_annual_mean &gt; 4.32: Yes (33/3)</span></span>
<span><span class="co">#&gt;                                             temp_annual_mean &lt;= 4.32:</span></span>
<span><span class="co">#&gt;                                             :...eastness &lt;= -75: Yes (2)</span></span>
<span><span class="co">#&gt;                                                 eastness &gt; -75: No (8)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Evaluation on training data (4832 cases):</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Decision Tree   </span></span>
<span><span class="co">#&gt;    ----------------  </span></span>
<span><span class="co">#&gt;    Size      Errors  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      49  349( 7.2%)   &lt;&lt;</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     (a)   (b)    &lt;-classified as</span></span>
<span><span class="co">#&gt;    ----  ----</span></span>
<span><span class="co">#&gt;    2585   129    (a): class Yes</span></span>
<span><span class="co">#&gt;     220  1898    (b): class No</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Attribute usage:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  100.00% county</span></span>
<span><span class="co">#&gt;   78.15% precip_annual</span></span>
<span><span class="co">#&gt;   71.94% dew_temp</span></span>
<span><span class="co">#&gt;   66.85% temp_annual_mean</span></span>
<span><span class="co">#&gt;   64.49% elevation</span></span>
<span><span class="co">#&gt;   62.93% latitude</span></span>
<span><span class="co">#&gt;   50.50% temp_annual_max</span></span>
<span><span class="co">#&gt;   47.91% roughness</span></span>
<span><span class="co">#&gt;   47.45% vapor_max</span></span>
<span><span class="co">#&gt;    9.93% longitude</span></span>
<span><span class="co">#&gt;    2.63% year</span></span>
<span><span class="co">#&gt;    2.46% temp_january_min</span></span>
<span><span class="co">#&gt;    2.30% vapor_min</span></span>
<span><span class="co">#&gt;    0.60% eastness</span></span>
<span><span class="co">#&gt;    0.56% temp_annual_min</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Time: 0.0 secs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> and <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> methods work in the same way as <code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart()</a></code>.</p>
<p>To fit (or tune) the tree using tidymodels, we can again use <code><a href="https://parsnip.tidymodels.org/reference/decision_tree.html">decision_tree()</a></code> but specify that the <code>"C5.0"</code> engine. While there are no arguments for the cost-complexity or tree depth, <code>min_n</code> is the primary tuning parameter. There is a <code>CF</code> argument in the control function, but this parameter rarely has a significant effect on the fit.</p>
<p>For example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">c5_res</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/decision_tree.html">decision_tree</a></span><span class="op">(</span>engine <span class="op">=</span> <span class="st">"C5.0"</span>, min_n <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_args.html">set_mode</a></span><span class="op">(</span><span class="st">"classification"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tune_grid</span><span class="op">(</span></span>
<span>    <span class="va">class</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>    resamples <span class="op">=</span> <span class="va">forested_rs</span>,</span>
<span>    grid <span class="op">=</span> <span class="fu">tibble</span><span class="op">(</span>min_n <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="fl">20</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">c5_res</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="cls-trees_files/figure-html/c5-tune-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>For this example, it prefers the deepest tree.</p>
<p><a href="https://aml4td.org/chapters/cls-trees.html#sec-cls-c50"><i class="fa-solid fa-rotate-left fa-small" aria-label="rotate-left"></i></a></p>
</section><section id="sec-cls-cit" class="level3" data-number="19.2.3"><h3 data-number="19.2.3" class="anchored" data-anchor-id="sec-cls-cit">
<span class="header-section-number">19.2.3</span> Conditional Inference Trees</h3>
<p>These models can be accessed with the <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span> package. The <code><a href="https://rdrr.io/pkg/partykit/man/ctree.html">ctree()</a></code> and possibly the <code><a href="https://rdrr.io/pkg/partykit/man/ctree_control.html">ctree_control()</a></code> functions are used to fit the model. The former takes a formula to fit the model. Important options in the control function are <code>testtype</code> (to specify the aspects of the test, such as using a Bonferroni correction), <code>alpha</code> (the significance method), <code>minsplit</code> (the minimum number of samples to contribute to splitting), and so on. Like <code><a href="https://rdrr.io/pkg/rpart/man/rpart.html">rpart()</a></code>, you can pass control options directly to <code><a href="https://rdrr.io/pkg/partykit/man/ctree.html">ctree()</a></code>.</p>
<p>There is one limitation for this model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">forested_train</span><span class="op">$</span><span class="va">county</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 39</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://partykit.r-forge.r-project.org/partykit/">partykit</a></span><span class="op">)</span></span>
<span><span class="co">#&gt; Loading required package: grid</span></span>
<span><span class="co">#&gt; Loading required package: libcoin</span></span>
<span><span class="co">#&gt; Loading required package: mvtnorm</span></span>
<span><span class="va">cit_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/partykit/man/ctree.html">ctree</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `doTest()`:</span></span>
<span><span class="co">#&gt; ! cannot search for unordered splits in &gt;= 31 levels</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can use a recipe step to limit the number of counties given to the model (see below).</p>
<p>To use this method via <span class="pkg"><a href="https://cran.r-project.org/package=tidymodels">tidymodels</a></span>, install and load the <span class="pkg"><a href="https://cran.r-project.org/package=bonsai">bonsai</a></span> package. Let’s make a recipe that uses <code>step_other()</code> to consolidate infrequently occurring counties. We’ll combine this with the model object within a workflow:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://bonsai.tidymodels.org/">bonsai</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">ctree_rec</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">step_other</span><span class="op">(</span><span class="va">county</span>, threshold <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span> <span class="co">#&lt;- determined by trying a few values</span></span>
<span></span>
<span><span class="va">ctree_fit</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">workflow</span><span class="op">(</span></span>
<span>    <span class="va">ctree_rec</span>,</span>
<span>    <span class="co"># Let's deliberately make a very shallow tree</span></span>
<span>    <span class="fu"><a href="https://parsnip.tidymodels.org/reference/decision_tree.html">decision_tree</a></span><span class="op">(</span>mode <span class="op">=</span> <span class="st">"classification"</span>, engine <span class="op">=</span> <span class="st">"partykit"</span>, min_n <span class="op">=</span> <span class="fl">1500</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">ctree_fit</span></span>
<span><span class="co">#&gt; ══ Workflow [trained] ═══════════════════════════════════════════════════════════════</span></span>
<span><span class="co">#&gt; Preprocessor: Recipe</span></span>
<span><span class="co">#&gt; Model: decision_tree()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Preprocessor ─────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; 1 Recipe Step</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; • step_other()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Model ────────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model formula:</span></span>
<span><span class="co">#&gt; ..y ~ year + elevation + eastness + northness + roughness + dew_temp + </span></span>
<span><span class="co">#&gt;     precip_annual + temp_annual_mean + temp_annual_min + temp_annual_max + </span></span>
<span><span class="co">#&gt;     temp_january_min + vapor_min + vapor_max + county + longitude + </span></span>
<span><span class="co">#&gt;     latitude</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Fitted party:</span></span>
<span><span class="co">#&gt; [1] root</span></span>
<span><span class="co">#&gt; |   [2] vapor_max &lt;= 1247</span></span>
<span><span class="co">#&gt; |   |   [3] county in chelan, king, kittitas, lincoln, pierce, skagit, snohomish, whatcom, whitman, other</span></span>
<span><span class="co">#&gt; |   |   |   [4] precip_annual &lt;= 1327: Yes (n = 616, err = 43%)</span></span>
<span><span class="co">#&gt; |   |   |   [5] precip_annual &gt; 1327: Yes (n = 1164, err = 13%)</span></span>
<span><span class="co">#&gt; |   |   [6] county in clallam, ferry, grays_harbor, lewis, okanogan, pend_oreille, stevens, yakima: Yes (n = 1172, err = 9%)</span></span>
<span><span class="co">#&gt; |   [7] vapor_max &gt; 1247</span></span>
<span><span class="co">#&gt; |   |   [8] county in adams, grant, kittitas, lincoln, okanogan, whitman, yakima, other</span></span>
<span><span class="co">#&gt; |   |   |   [9] precip_annual &lt;= 358: No (n = 1119, err = 1%)</span></span>
<span><span class="co">#&gt; |   |   |   [10] precip_annual &gt; 358: No (n = 522, err = 20%)</span></span>
<span><span class="co">#&gt; |   |   [11] county in chelan, ferry, pend_oreille, stevens: Yes (n = 239, err = 32%)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of inner nodes:    5</span></span>
<span><span class="co">#&gt; Number of terminal nodes: 6</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span> package has an excellent visualization tool</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ctree_fit</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://hardhat.tidymodels.org/reference/hardhat-extract.html">extract_fit_engine</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="co"># Use an option to vertically offset the labels so that they</span></span>
<span>  <span class="co"># do not overlap</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>ep_args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>justmin <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="cls-trees_files/figure-html/ctree-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>There is an <code><a href="https://rdrr.io/pkg/partykit/man/party-coercion.html">as.party()</a></code> method that can work with <code>rpart</code> and <code>C5.0</code> model objects. After converting those models to the party format, you can use the plot function for them.</p>
</section><section id="sec-cls-tree-global" class="level3" data-number="19.2.4"><h3 data-number="19.2.4" class="anchored" data-anchor-id="sec-cls-tree-global">
<span class="header-section-number">19.2.4</span> Globally Estimated Trees</h3>
<p>The <span class="pkg"><a href="https://cran.r-project.org/package=evtree">evtree</a></span> package, based on <span class="pkg"><a href="https://cran.r-project.org/package=partykit">partykit</a></span>, can use genetic algorithms to train decision trees. It has a formula methods an includes arguments for:</p>
<ul>
<li><p><code>minsplit</code>: “the minimum sum of weights in a node in order to be considered for splitting.”</p></li>
<li><p><code>maxdepth</code>: “maximum depth of the tree. Note, that the memory requirements increase by the square of the maximum tree depth.”</p></li>
<li><p><code>niterations</code>: “in case the run does not converge, it terminates after a specified number of iterations defined by niterations.”</p></li>
<li><p><code>ntrees</code>: “the number of trees in the population.</p></li>
<li><p><code>alpha</code>: regulates the complexity part of the cost function. Increasing values of alpha encourage decreasing tree sizes.”</p></li>
</ul>
<p>There are also parameters for the genetic algorithm operators (e.g., mutation rate, etc.).</p>
<p>Here’s an example where we deliberately limit the tree size (in order to show a plot):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">evtree</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">8375</span><span class="op">)</span></span>
<span><span class="va">ga_tree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/evtree/man/evtree.html">evtree</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span>, maxdepth <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">ga_tree</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Model formula:</span></span>
<span><span class="co">#&gt; class ~ year + elevation + eastness + northness + roughness + </span></span>
<span><span class="co">#&gt;     dew_temp + precip_annual + temp_annual_mean + temp_annual_min + </span></span>
<span><span class="co">#&gt;     temp_annual_max + temp_january_min + vapor_min + vapor_max + </span></span>
<span><span class="co">#&gt;     county + longitude + latitude</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Fitted party:</span></span>
<span><span class="co">#&gt; [1] root</span></span>
<span><span class="co">#&gt; |   [2] latitude &lt; 47.77</span></span>
<span><span class="co">#&gt; |   |   [3] precip_annual &lt; 626: No (n = 1545, err = 6%)</span></span>
<span><span class="co">#&gt; |   |   [4] precip_annual &gt;= 626: Yes (n = 1602, err = 15%)</span></span>
<span><span class="co">#&gt; |   [5] latitude &gt;= 47.77</span></span>
<span><span class="co">#&gt; |   |   [6] precip_annual &lt; 359: No (n = 155, err = 14%)</span></span>
<span><span class="co">#&gt; |   |   [7] precip_annual &gt;= 359: Yes (n = 1530, err = 19%)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of inner nodes:    3</span></span>
<span><span class="co">#&gt; Number of terminal nodes: 4</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Visually:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">ga_tree</span>, ep_args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>justmin <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="cls-trees_files/figure-html/evree-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Currently, there is no tidymodels interface for this model.</p>
<p><a href="https://aml4td.org/chapters/cls-trees.html#sec-cls-global"><i class="fa-solid fa-rotate-left fa-small" aria-label="rotate-left"></i></a></p>
</section><section id="sec-cls-oblique" class="level3" data-number="19.2.5"><h3 data-number="19.2.5" class="anchored" data-anchor-id="sec-cls-oblique">
<span class="header-section-number">19.2.5</span> Oblique Trees</h3>
<p>Oblique trees can be fit using a package intended for random forest models called <span class="pkg"><a href="https://cran.r-project.org/package=aorsf">aorsf</a></span>. To fit a single decision tree:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/aorsf">aorsf</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Directly:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">82</span><span class="op">)</span></span>
<span><span class="va">obl_tree</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://docs.ropensci.org/aorsf/reference/orsf.html">orsf</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span>, n_tree <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Via Tidymodels, also requires the bonsai package:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">82</span><span class="op">)</span></span>
<span><span class="va">obl_tm_tree</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/rand_forest.html">rand_forest</a></span><span class="op">(</span>mode <span class="op">=</span> <span class="st">"classification"</span>, engine <span class="op">=</span> <span class="st">"aorsf"</span>, trees <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">obl_tree</span></span>
<span><span class="co">#&gt; ---------- Oblique random classification forest</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      Linear combinations: Accelerated Logistic regression</span></span>
<span><span class="co">#&gt;           N observations: 4832</span></span>
<span><span class="co">#&gt;                N classes: 2</span></span>
<span><span class="co">#&gt;                  N trees: 1</span></span>
<span><span class="co">#&gt;       N predictors total: 16</span></span>
<span><span class="co">#&gt;    N predictors per node: 8</span></span>
<span><span class="co">#&gt;  Average leaves per tree: 79</span></span>
<span><span class="co">#&gt; Min observations in leaf: 5</span></span>
<span><span class="co">#&gt;           OOB stat value: 0.90</span></span>
<span><span class="co">#&gt;            OOB stat type: AUC-ROC</span></span>
<span><span class="co">#&gt;      Variable importance: anova</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; -----------------------------------------</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>There is no interface for printing or plotting a single tree, although we can check its variable importance:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">obl_tree</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/aorsf/reference/orsf_vi.html">orsf_vi</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/enframe.html">enframe</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">16</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 16 × 2</span></span>
<span><span class="co">#&gt;    name               value</span></span>
<span><span class="co">#&gt;    &lt;chr&gt;              &lt;dbl&gt;</span></span>
<span><span class="co">#&gt;  1 precip_annual    0.35   </span></span>
<span><span class="co">#&gt;  2 dew_temp         0.2222 </span></span>
<span><span class="co">#&gt;  3 latitude         0.1923 </span></span>
<span><span class="co">#&gt;  4 temp_annual_max  0.1579 </span></span>
<span><span class="co">#&gt;  5 longitude        0.15   </span></span>
<span><span class="co">#&gt;  6 roughness        0.12   </span></span>
<span><span class="co">#&gt;  7 county           0.1136 </span></span>
<span><span class="co">#&gt;  8 temp_january_min 0.09091</span></span>
<span><span class="co">#&gt;  9 eastness         0.08696</span></span>
<span><span class="co">#&gt; 10 vapor_max        0.07407</span></span>
<span><span class="co">#&gt; 11 elevation        0.06897</span></span>
<span><span class="co">#&gt; 12 temp_annual_mean 0.06667</span></span>
<span><span class="co">#&gt; 13 northness        0.03571</span></span>
<span><span class="co">#&gt; 14 vapor_min        0      </span></span>
<span><span class="co">#&gt; 15 temp_annual_min  0      </span></span>
<span><span class="co">#&gt; 16 year             0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>There are several other packages on CRAN to fit similar models, <span class="pkg"><a href="https://cran.r-project.org/package=LDATree">LDATree</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=ODRF">ODRF</a></span>, and <span class="pkg"><a href="https://cran.r-project.org/package=PPforest">PPforest</a></span>, as well as the archived package <span class="pkg"><a href="https://cran.r-project.org/package=nodeHarvest">nodeHarvest</a></span>.</p>
<p><a href="https://aml4td.org/chapters/cls-trees.html#sec-cls-oblique"><i class="fa-solid fa-rotate-left fa-small" aria-label="rotate-left"></i></a></p>
</section></section><section id="sec-cls-rules" class="level2" data-number="19.3"><h2 data-number="19.3" class="anchored" data-anchor-id="sec-cls-rules">
<span class="header-section-number">19.3</span> Rule-Based Models</h2>
<p>C5.0 rules can also be fit using the <span class="pkg"><a href="https://cran.r-project.org/package=C50">C50</a></span> package, using the <code>rules = TRUE</code> option. As an example:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://topepo.github.io/C5.0/">C50</a></span><span class="op">)</span></span>
<span><span class="va">c5_rules_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://topepo.github.io/C5.0/reference/C5.0.html">C5.0</a></span><span class="op">(</span><span class="va">class</span> <span class="op">~</span> <span class="va">.</span>, rules <span class="op">=</span> <span class="cn">TRUE</span>, data <span class="op">=</span> <span class="va">forested_train</span><span class="op">)</span></span>
<span><span class="va">c5_rules_fit</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; C5.0.formula(formula = class ~ ., data = forested_train, rules = TRUE)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule-Based Model</span></span>
<span><span class="co">#&gt; Number of samples: 4832 </span></span>
<span><span class="co">#&gt; Number of predictors: 16 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Rules: 22 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Non-standard options: attempt to group attributes</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">c5_rules_fit</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; C5.0.formula(formula = class ~ ., data = forested_train, rules = TRUE)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; C5.0 [Release 2.07 GPL Edition]      Fri May 22 12:49:40 2026</span></span>
<span><span class="co">#&gt; -------------------------------</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Class specified by attribute `outcome'</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Read 4832 cases (17 attributes) from undefined.data</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rules:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 1: (39/1, lift 1.7)</span></span>
<span><span class="co">#&gt;  dew_temp &lt;= 6.99</span></span>
<span><span class="co">#&gt;  precip_annual &gt; 1910</span></span>
<span><span class="co">#&gt;  temp_annual_mean &gt; 10.69</span></span>
<span><span class="co">#&gt;  -&gt;  class Yes  [0.951]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 2: (1973/133, lift 1.7)</span></span>
<span><span class="co">#&gt;  elevation &gt; 32</span></span>
<span><span class="co">#&gt;  roughness &gt; 15</span></span>
<span><span class="co">#&gt;  dew_temp &gt; -4.05</span></span>
<span><span class="co">#&gt;  precip_annual &gt; 630</span></span>
<span><span class="co">#&gt;  county in {asotin, chelan, clallam, clark, columbia, cowlitz, ferry,</span></span>
<span><span class="co">#&gt;                    garfield, grays_harbor, island, jefferson, king, kitsap,</span></span>
<span><span class="co">#&gt;                    kittitas, klickitat, lewis, mason, okanogan, pacific,</span></span>
<span><span class="co">#&gt;                    pend_oreille, pierce, san_juan, skagit, skamania, snohomish,</span></span>
<span><span class="co">#&gt;                    spokane, stevens, thurston, wahkiakum, whatcom, yakima}</span></span>
<span><span class="co">#&gt;  latitude &gt; 45.73898</span></span>
<span><span class="co">#&gt;  -&gt;  class Yes  [0.932]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 3: (33/2, lift 1.6)</span></span>
<span><span class="co">#&gt;  roughness &gt; 18</span></span>
<span><span class="co">#&gt;  precip_annual &gt; 464</span></span>
<span><span class="co">#&gt;  temp_january_min &lt;= 3.78</span></span>
<span><span class="co">#&gt;  county = spokane</span></span>
<span><span class="co">#&gt;  latitude &gt; 47.53998</span></span>
<span><span class="co">#&gt;  -&gt;  class Yes  [0.914]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 4: (494/57, lift 1.6)</span></span>
<span><span class="co">#&gt;  county in {clallam, ferry, stevens}</span></span>
<span><span class="co">#&gt;  -&gt;  class Yes  [0.883]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 5: (3776/1076, lift 1.3)</span></span>
<span><span class="co">#&gt;  county in {asotin, chelan, clallam, clark, columbia, cowlitz, ferry,</span></span>
<span><span class="co">#&gt;                    garfield, grays_harbor, island, jefferson, king, kitsap,</span></span>
<span><span class="co">#&gt;                    kittitas, klickitat, lewis, mason, okanogan, pacific,</span></span>
<span><span class="co">#&gt;                    pend_oreille, pierce, san_juan, skagit, skamania, snohomish,</span></span>
<span><span class="co">#&gt;                    spokane, stevens, thurston, wahkiakum, whatcom, yakima}</span></span>
<span><span class="co">#&gt;  -&gt;  class Yes  [0.715]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 6: (1056/14, lift 2.2)</span></span>
<span><span class="co">#&gt;  county in {adams, benton, douglas, franklin, grant, lincoln,</span></span>
<span><span class="co">#&gt;                    walla_walla, whitman}</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.986]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 7: (99/1, lift 2.2)</span></span>
<span><span class="co">#&gt;  precip_annual &lt;= 630</span></span>
<span><span class="co">#&gt;  temp_january_min &gt; 3.78</span></span>
<span><span class="co">#&gt;  county in {asotin, columbia, garfield, island}</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.980]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 8: (1053/35, lift 2.2)</span></span>
<span><span class="co">#&gt;  temp_annual_min &gt; -4.92</span></span>
<span><span class="co">#&gt;  temp_annual_max &gt; 15</span></span>
<span><span class="co">#&gt;  longitude &gt; -120.6273</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.966]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 9: (512/29, lift 2.1)</span></span>
<span><span class="co">#&gt;  elevation &gt; 32</span></span>
<span><span class="co">#&gt;  roughness &lt;= 45</span></span>
<span><span class="co">#&gt;  temp_annual_mean &gt; 10.62</span></span>
<span><span class="co">#&gt;  longitude &gt; -122.5701</span></span>
<span><span class="co">#&gt;  latitude &gt; 45.73898</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.942]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 10: (701/41, lift 2.1)</span></span>
<span><span class="co">#&gt;  temp_annual_max &gt; 16.49</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.940]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 11: (524/31, lift 2.1)</span></span>
<span><span class="co">#&gt;  elevation &gt; 32</span></span>
<span><span class="co">#&gt;  roughness &lt;= 45</span></span>
<span><span class="co">#&gt;  temp_annual_mean &gt; 10.62</span></span>
<span><span class="co">#&gt;  longitude &gt; -122.5701</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.939]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 12: (1477/90, lift 2.1)</span></span>
<span><span class="co">#&gt;  dew_temp &gt; 0.03</span></span>
<span><span class="co">#&gt;  precip_annual &lt;= 464</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.938]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 13: (11, lift 2.1)</span></span>
<span><span class="co">#&gt;  year &lt;= 2013</span></span>
<span><span class="co">#&gt;  eastness &lt;= -63</span></span>
<span><span class="co">#&gt;  precip_annual &lt;= 464</span></span>
<span><span class="co">#&gt;  county = okanogan</span></span>
<span><span class="co">#&gt;  latitude &gt; 48.45825</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.923]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 14: (9, lift 2.1)</span></span>
<span><span class="co">#&gt;  eastness &gt; -75</span></span>
<span><span class="co">#&gt;  roughness &gt; 191</span></span>
<span><span class="co">#&gt;  temp_annual_mean &lt;= 4.32</span></span>
<span><span class="co">#&gt;  temp_annual_max &gt; 6.84</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.909]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 15: (30/2, lift 2.1)</span></span>
<span><span class="co">#&gt;  precip_annual &gt; 464</span></span>
<span><span class="co">#&gt;  precip_annual &lt;= 630</span></span>
<span><span class="co">#&gt;  vapor_min &lt;= 232</span></span>
<span><span class="co">#&gt;  county in {asotin, columbia, garfield, spokane}</span></span>
<span><span class="co">#&gt;  latitude &lt;= 47.53998</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.906]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 16: (54/6, lift 2.0)</span></span>
<span><span class="co">#&gt;  dew_temp &lt;= -4.05</span></span>
<span><span class="co">#&gt;  longitude &lt;= -120.5846</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.875]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 17: (35/4, lift 2.0)</span></span>
<span><span class="co">#&gt;  elevation &lt;= 32</span></span>
<span><span class="co">#&gt;  dew_temp &gt; 6.99</span></span>
<span><span class="co">#&gt;  temp_annual_mean &gt; 10.69</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.865]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 18: (34/4, lift 2.0)</span></span>
<span><span class="co">#&gt;  county in {clark, klickitat}</span></span>
<span><span class="co">#&gt;  latitude &lt;= 45.73898</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.861]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 19: (107/18, lift 1.9)</span></span>
<span><span class="co">#&gt;  elevation &lt;= 32</span></span>
<span><span class="co">#&gt;  precip_annual &gt; 464</span></span>
<span><span class="co">#&gt;  precip_annual &lt;= 1910</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.826]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 20: (21/3, lift 1.9)</span></span>
<span><span class="co">#&gt;  roughness &gt; 191</span></span>
<span><span class="co">#&gt;  temp_annual_mean &lt;= 4.32</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.826]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 21: (54/10, lift 1.8)</span></span>
<span><span class="co">#&gt;  roughness &lt;= 4</span></span>
<span><span class="co">#&gt;  temp_annual_mean &lt;= 10.62</span></span>
<span><span class="co">#&gt;  vapor_min &lt;= 106</span></span>
<span><span class="co">#&gt;  vapor_max &lt;= 1201</span></span>
<span><span class="co">#&gt;  longitude &gt; -122.6583</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.804]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rule 22: (136/28, lift 1.8)</span></span>
<span><span class="co">#&gt;  year &gt; 2010</span></span>
<span><span class="co">#&gt;  roughness &lt;= 15</span></span>
<span><span class="co">#&gt;  county in {asotin, clark, columbia, garfield, island, spokane, thurston}</span></span>
<span><span class="co">#&gt;  -&gt;  class No  [0.790]</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Default class: Yes</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Evaluation on training data (4832 cases):</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Rules     </span></span>
<span><span class="co">#&gt;    ----------------</span></span>
<span><span class="co">#&gt;      No      Errors</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      22  387( 8.0%)   &lt;&lt;</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     (a)   (b)    &lt;-classified as</span></span>
<span><span class="co">#&gt;    ----  ----</span></span>
<span><span class="co">#&gt;    2555   159    (a): class Yes</span></span>
<span><span class="co">#&gt;     228  1890    (b): class No</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Attribute usage:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  100.00% county</span></span>
<span><span class="co">#&gt;   75.87% precip_annual</span></span>
<span><span class="co">#&gt;   73.53% dew_temp</span></span>
<span><span class="co">#&gt;   54.88% roughness</span></span>
<span><span class="co">#&gt;   53.37% elevation</span></span>
<span><span class="co">#&gt;   52.48% latitude</span></span>
<span><span class="co">#&gt;   26.28% longitude</span></span>
<span><span class="co">#&gt;   24.21% temp_annual_max</span></span>
<span><span class="co">#&gt;   21.79% temp_annual_min</span></span>
<span><span class="co">#&gt;   13.87% temp_annual_mean</span></span>
<span><span class="co">#&gt;    3.04% year</span></span>
<span><span class="co">#&gt;    2.73% temp_january_min</span></span>
<span><span class="co">#&gt;    1.74% vapor_min</span></span>
<span><span class="co">#&gt;    1.12% vapor_max</span></span>
<span><span class="co">#&gt;    0.41% eastness</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Time: 0.1 secs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <span class="pkg"><a href="https://cran.r-project.org/package=rules">rules</a></span> package contains a <span class="pkg"><a href="https://cran.r-project.org/package=parsnip">parsnip</a></span> model function called <code><a href="https://parsnip.tidymodels.org/reference/C5_rules.html">C5_rules()</a></code>.</p>
<p><a href="https://aml4td.org/chapters/cls-trees.html#sec-cls-rules"><i class="fa-solid fa-rotate-left fa-small" aria-label="rotate-left"></i></a></p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/tidymodels\.aml4td\.org\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../chapters/cls-neural-nets.html" class="pagination-link" aria-label="Neural Network Classifiers">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Neural Network Classifiers</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>