# News {.unlisted .unnumbered}

## Changelog {.unlisted .unnumbered}

## 2026-05-22

The main chapter on classification trees (@sec-cls-trees) was added. 

The sections on neural networks were relocated to be in their own chapter (@sec-cls-neural-nets). 

## 2026-01-26

New sections on

- @sec-logistic-reg
- @sec-nonlinear-da, such as 
  - @sec-naive-bayes
  - @sec-fda
- @sec-cls-knn
- @sec-cls-nnet

## 2025-07-25

Part 4 has begun with @sec-cls-metrics.

## 2025-06-24

A new chapter (@sec-comparing-models) on model comparisons was added, concluding Part 3 of the book.  

## 2025-05-21

New chapters on iterative optimization and feature selection. 

Whenever a section has a corresponding computing supplement, an icon on the main site is shown that directly links to that section.  In this computing supplement, you can get back to the main site's section via this icon: {{< fa solid rotate-left >}}.

We also move to [mirai](https://mirai.r-lib.org/index.html) for parallel processing. 

## 2025-01-17 {.unlisted .unnumbered}

Small update that standardized the url anchors. 

Some sections were reorganized. 

## 2024-09-23 {.unlisted .unnumbered}

Computing chapters caught up to the website (chapter 11, grid search)

## 2023-12-11 {.unlisted .unnumbered}

Added a chapter on initial data splitting.
