<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.4">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Tidymodels Computing Supplement – 2&nbsp; The Whole Game</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/initial-data-splitting.html" rel="next">
<link href="../chapters/introduction.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span id="sec-whole-game" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Whole Game</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../"></a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/aml4td/computing-tidymodels/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/news.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">News</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/contributing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/whole-game.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Whole Game</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Preparation</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/initial-data-splitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Initial Data Splitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/numeric-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transforming Numeric Predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/categorical-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with Categorical Predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Optmization</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Classification</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regression</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Characterization</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Finalization</span></span>
  </li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#requirements" id="toc-requirements" class="nav-link active" data-scroll-target="#requirements"><span class="header-section-number">2.1</span> Requirements</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">2.2</span> The Data</a></li>
  <li><a href="#data-spending" id="toc-data-spending" class="nav-link" data-scroll-target="#data-spending"><span class="header-section-number">2.3</span> Data Spending</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">2.4</span> Exploratory Data Analysis</a></li>
  <li>
<a href="#model-development" id="toc-model-development" class="nav-link" data-scroll-target="#model-development"><span class="header-section-number">2.5</span> Model Development</a>
  <ul class="collapse">
<li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#rule-based-ensemble" id="toc-rule-based-ensemble" class="nav-link" data-scroll-target="#rule-based-ensemble">Rule-Based Ensemble</a></li>
  <li><a href="#neural-network" id="toc-neural-network" class="nav-link" data-scroll-target="#neural-network">Neural Network</a></li>
  </ul>
</li>
  <li><a href="#aside-parallel-processing" id="toc-aside-parallel-processing" class="nav-link" data-scroll-target="#aside-parallel-processing"><span class="header-section-number">2.6</span> Aside: Parallel Processing</a></li>
  <li><a href="#calibration" id="toc-calibration" class="nav-link" data-scroll-target="#calibration"><span class="header-section-number">2.7</span> Calibration</a></li>
  <li><a href="#test-set-results" id="toc-test-set-results" class="nav-link" data-scroll-target="#test-set-results"><span class="header-section-number">2.8</span> Test Set Results</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">2.9</span> Conclusion</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block"><span id="sec-whole-game" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Whole Game</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>This chapter on the main website is a high-level tour of the modeling process. We’ll follow the same pattern here by analyzing the same data. We won’t reproduce every figure or table but these notes will give you a broad understanding of how the tidymodels framework operates.</p>
<section id="requirements" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="requirements">
<span class="header-section-number">2.1</span> Requirements</h2>
<p>You’ll need 6 packages (<span class="pkg"><a href="https://cran.r-project.org/package=brulee">brulee</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=Cubist">Cubist</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=patchwork">patchwork</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=scales">scales</a></span>, <span class="pkg"><a href="https://cran.r-project.org/package=splines2">splines2</a></span>, and <span class="pkg"><a href="https://cran.r-project.org/package=tidymodels">tidymodels</a></span>) for this chapter. You can install them via:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pak</span><span class="fu">::</span><span class="fu"><a href="https://pak.r-lib.org/reference/pak.html">pak</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"brulee"</span>, <span class="st">"Cubist"</span>, <span class="st">"patchwork"</span>, <span class="st">"scales"</span>, <span class="st">"splines2"</span>, <span class="st">"tidymodels"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you’ve installed <span class="pkg"><a href="https://cran.r-project.org/package=brulee">brulee</a></span>, you should load it using <code><a href="https://github.com/tidymodels/brulee">library(brulee)</a></code> to install the underlying <code>torch</code> executables. You only have to do this once.</p>
<p>Two other packages are described but not directly used: <span class="pkg"><a href="https://cran.r-project.org/package=parallel">parallel</a></span> and <span class="pkg"><a href="https://cran.r-project.org/package=doParallel">doParallel</a></span>.</p>
<p>Let’s run some code to get started:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidymodels.tidymodels.org">tidymodels</a></span><span class="op">)</span></span>
<span><span class="co">#&gt; ── Attaching packages ─────────────────────────────────────────── tidymodels 1.2.0 ──</span></span>
<span><span class="co">#&gt; ✔ broom        1.0.5      ✔ recipes      1.0.10</span></span>
<span><span class="co">#&gt; ✔ dials        1.2.1      ✔ rsample      1.2.1 </span></span>
<span><span class="co">#&gt; ✔ dplyr        1.1.4      ✔ tibble       3.2.1 </span></span>
<span><span class="co">#&gt; ✔ ggplot2      3.5.0      ✔ tidyr        1.3.1 </span></span>
<span><span class="co">#&gt; ✔ infer        1.0.7      ✔ tune         1.2.0 </span></span>
<span><span class="co">#&gt; ✔ modeldata    1.3.0      ✔ workflows    1.1.4 </span></span>
<span><span class="co">#&gt; ✔ parsnip      1.2.1      ✔ workflowsets 1.1.0 </span></span>
<span><span class="co">#&gt; ✔ purrr        1.0.2      ✔ yardstick    1.3.1</span></span>
<span><span class="co">#&gt; ── Conflicts ────────────────────────────────────────────── tidymodels_conflicts() ──</span></span>
<span><span class="co">#&gt; ✖ purrr::discard() masks scales::discard()</span></span>
<span><span class="co">#&gt; ✖ dplyr::filter()  masks stats::filter()</span></span>
<span><span class="co">#&gt; ✖ dplyr::lag()     masks stats::lag()</span></span>
<span><span class="co">#&gt; ✖ recipes::step()  masks stats::step()</span></span>
<span><span class="co">#&gt; • Dig deeper into tidy modeling with R at https://www.tmwr.org</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/probably">probably</a></span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Attaching package: 'probably'</span></span>
<span><span class="co">#&gt; The following objects are masked from 'package:base':</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     as.factor, as.ordered</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://tidymodels.tidymodels.org/reference/tidymodels_prefer.html">tidymodels_prefer</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, this note:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>All of these notes will assume that you have an R session that is running from the root of the directory containing the GitHub repository files. In other words, if you were to execute <code>list.dirs(recursive = FALSE)</code>, the output would show entries such as <code>"./chapters"</code>, <code>"./RData"</code>, etc.</p>
<p>If you are not in the right place, use <code><a href="https://rdrr.io/r/base/getwd.html">setwd()</a></code> to change the working directory to the correct location.</p>
<p>If you start by opening the <code>Rproj</code> file, you will always start in the right place.</p>
</div>
</div>
</section><section id="the-data" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="the-data">
<span class="header-section-number">2.2</span> The Data</h2>
<p>The data set is pre-compiled into a binary format R uses (called “RData format” here). It is in the <code>RData</code> directory. A <code>csv</code> version is also in the <code>delimited</code> directory. Let’s load it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span><span class="st">"RData/deliveries.RData"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are a lot of ways that you can examine the contents of an object. <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> is good for data frames; in the RStudio IDE, it opens a spreadsheet-like viewer. <code><a href="https://pillar.r-lib.org/reference/glimpse.html">tibble::glimpse()</a></code> shows more details about the object, such as classes, but can be a bad choice if you have &gt;50 columns in the data (or if it is a long list or similar). We’ll use that:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glimpse</span><span class="op">(</span><span class="va">deliveries</span><span class="op">)</span></span>
<span><span class="co">#&gt; Rows: 10,012</span></span>
<span><span class="co">#&gt; Columns: 31</span></span>
<span><span class="co">#&gt; $ time_to_delivery &lt;dbl&gt; 16.11, 22.95, 30.29, 33.43, 27.23, 19.65, 22.10, 26.63, 3…</span></span>
<span><span class="co">#&gt; $ hour             &lt;dbl&gt; 11.90, 19.23, 18.37, 15.84, 19.62, 12.95, 15.48, 17.05, 1…</span></span>
<span><span class="co">#&gt; $ day              &lt;fct&gt; Thu, Tue, Fri, Thu, Fri, Sat, Sun, Thu, Fri, Sun, Tue, Fr…</span></span>
<span><span class="co">#&gt; $ distance         &lt;dbl&gt; 3.15, 3.69, 2.06, 5.97, 2.52, 3.35, 2.46, 2.21, 2.62, 2.7…</span></span>
<span><span class="co">#&gt; $ item_01          &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_02          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, …</span></span>
<span><span class="co">#&gt; $ item_03          &lt;int&gt; 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_04          &lt;int&gt; 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_05          &lt;int&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_06          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, …</span></span>
<span><span class="co">#&gt; $ item_07          &lt;int&gt; 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, …</span></span>
<span><span class="co">#&gt; $ item_08          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_09          &lt;int&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_10          &lt;int&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_11          &lt;int&gt; 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_12          &lt;int&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_13          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_14          &lt;int&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_15          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_16          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_17          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_18          &lt;int&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_19          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_20          &lt;int&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_21          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_22          &lt;int&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, …</span></span>
<span><span class="co">#&gt; $ item_23          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_24          &lt;int&gt; 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_25          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, …</span></span>
<span><span class="co">#&gt; $ item_26          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, …</span></span>
<span><span class="co">#&gt; $ item_27          &lt;int&gt; 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, …</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that this is a data frame and, more specifically a specialized version called a <a href="https://tibble.tidyverse.org">tibble</a>. There are 10,012 data points and 31 columns and their types.</p>
<p>Note that the <code>day</code> column is a <a href="https://r4ds.hadley.nz/factors"><em>factor</em></a>. This is the preferred way to represent most categorical data (for modeling, at least). A factor catalogs the possible values of the data and stores those <em>levels</em>. That is important when we convert categorical predictors to “dummy variables” or “indicators” and similar operations.</p>
<p>In some cases, storing categorical data as integers might seem like a good idea (especially 0/1 for binary data). Do your best <em>to avoid that</em>. R (and tidymodels) would instead you use a data type that is designed explicitly for categories (a factor); it knows what to do with factors. If an integer is used, R can’t distinguish this from a column of counts (such as the number of times that <code>item_01</code> was included in the order).</p>
<p>To create the histograms of the delivery times, we used this code to create each:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Setup some fancy code for the axes: </span></span>
<span><span class="va">log_2_breaks</span> <span class="op">&lt;-</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/trans_breaks.html">trans_breaks</a></span><span class="op">(</span><span class="st">"log2"</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fl">2</span><span class="op">^</span><span class="va">x</span><span class="op">)</span></span>
<span><span class="va">log_2_labs</span>   <span class="op">&lt;-</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/trans_format.html">trans_format</a></span><span class="op">(</span><span class="st">"log2"</span>, <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/parse_format.html">math_format</a></span><span class="op">(</span><span class="fl">2</span><span class="op">^</span><span class="va">.x</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_hist</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">deliveries</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">time_to_delivery</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">30</span>, col <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_rug</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, title <span class="op">=</span> <span class="st">"(a)"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_log_hist</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">deliveries</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">time_to_delivery</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">30</span>, col <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_rug</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, title <span class="op">=</span> <span class="st">"(b)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_log10</span><span class="op">(</span>breaks <span class="op">=</span> <span class="va">log_2_breaks</span>, labels <span class="op">=</span> <span class="va">log_2_labs</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You don’t need to assign the plots to objects; you can just print each. We did this so that we can concatenate the two plots with the <span class="pkg"><a href="https://cran.r-project.org/package=patchwork">patchwork</a></span> package<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">delivery_hist</span> <span class="op">+</span> <span class="va">delivery_log_hist</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/whole-game-hists-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the code above, we use an option called <code>"alpha"</code>. This is jargon for transparency; a value of <code>1/4</code> means that the points in the rug are 25% opaque.</p>
</section><section id="data-spending" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="data-spending">
<span class="header-section-number">2.3</span> Data Spending</h2>
<p>tidymodels has a variety of ways to split the data at the outset of your modeling project. We will create a three-way split of the data using a function called <code>initial_validation_split()</code>.</p>
<p>It uses random numbers so we will set the random number seed before using it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What’s a random number seed?
</div>
</div>
<div class="callout-body-container callout-body">
<p>We are using random numbers (actually <a href="https://en.wikipedia.org/wiki/Pseudorandomness">pseudo-random numbers</a>). We want to get the same “random” values every time we run the same code for reproducibility. To do that, we use the <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> function and give it an integer value. The value itself doesn’t matter.</p>
<p>The random number stream is like a river. If you want to see the same things in your journey down the river, you must get in at the same exact spot. The seed is like the location where you start a journey (that is always the same).</p>
</div>
</div>
<p>The code is below.</p>
<ul>
<li><p>The <code>prop</code> argument shows the fraction of the original data that should go into the training set (60%) and the validation set (20%). The remaining 20% are put in the test set.</p></li>
<li><p>The <code>strata</code> argument specifies that the splitting should consider the outcome column (<code>time_to_delivery</code>). This will be discussed in a future section. In short, the three-way splitting is done in different regions of the outcome data in a way that makes the distribution of the outcome as similar as possible across the three partitions.</p></li>
</ul>
<p>We used a value of 991 to set the seed<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">991</span><span class="op">)</span></span>
<span><span class="va">delivery_split</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">initial_validation_split</span><span class="op">(</span><span class="va">deliveries</span>, prop <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.6</span>, <span class="fl">0.2</span><span class="op">)</span>, strata <span class="op">=</span> <span class="va">time_to_delivery</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># What is in it? </span></span>
<span><span class="va">delivery_split</span></span>
<span><span class="co">#&gt; &lt;Training/Validation/Testing/Total&gt;</span></span>
<span><span class="co">#&gt; &lt;6004/2004/2004/10012&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This object records which rows of the original data go into the training, validation, or test sets. The printed output shows the totals for each as <code>&lt;train/val/test/total&gt;</code>.</p>
<p>To get the data frames with the correct rows, use these three eponymous functions:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">delivery_train</span> <span class="op">&lt;-</span> <span class="fu">training</span><span class="op">(</span><span class="va">delivery_split</span><span class="op">)</span></span>
<span><span class="va">delivery_test</span>  <span class="op">&lt;-</span> <span class="fu">testing</span><span class="op">(</span><span class="va">delivery_split</span><span class="op">)</span></span>
<span><span class="va">delivery_val</span>   <span class="op">&lt;-</span> <span class="fu">validation</span><span class="op">(</span><span class="va">delivery_split</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will mostly work with the training set of 6,004 deliveries. We’ll use that to explore the data, fit models, and so on.</p>
</section><section id="exploratory-data-analysis" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">2.4</span> Exploratory Data Analysis</h2>
<p>We mostly used <span class="pkg"><a href="https://cran.r-project.org/package=ggplot2">ggplot2</a></span> and <span class="pkg"><a href="https://cran.r-project.org/package=patchwork">patchwork</a></span> to create these graphics:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Make specific colors for each day</span></span>
<span><span class="va">day_cols</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#000000FF"</span>, <span class="st">"#24FF24FF"</span>, <span class="st">"#009292FF"</span>,  <span class="st">"#B66DFFFF"</span>, </span>
<span>               <span class="st">"#6DB6FFFF"</span>, <span class="st">"#920000FF"</span>, <span class="st">"#FFB6DBFF"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_dist</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">delivery_train</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">distance</span>, <span class="va">time_to_delivery</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">10</span>, cex <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, x <span class="op">=</span> <span class="st">"Distance (miles)"</span>, title <span class="op">=</span> <span class="st">"(a)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># This function creates the smooth trend line. The `se` option shuts off the</span></span>
<span>  <span class="co"># confidence band around the line; too much information to put into one plot. </span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_day</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">delivery_train</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">day</span>, <span class="va">time_to_delivery</span>, col <span class="op">=</span> <span class="va">day</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span>show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, x <span class="op">=</span> <span class="cn">NULL</span>, title <span class="op">=</span> <span class="st">"(c)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_color_manual</span><span class="op">(</span>values <span class="op">=</span> <span class="va">day_cols</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_time</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">delivery_train</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">hour</span>, <span class="va">time_to_delivery</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, x <span class="op">=</span> <span class="st">"Order Time (decimal hours)"</span>, title <span class="op">=</span> <span class="st">"(b)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">10</span>, cex <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">delivery_time_day</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">delivery_train</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">hour</span>, <span class="va">time_to_delivery</span>, col <span class="op">=</span> <span class="va">day</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Time Until Delivery (min)"</span>, x <span class="op">=</span> <span class="st">"Order Time (decimal hours)"</span>, title <span class="op">=</span> <span class="st">"(d)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># With `col = day`, the trends will be estimated separately for each value of 'day'.</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_color_manual</span><span class="op">(</span>values <span class="op">=</span> <span class="va">day_cols</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="pkg"><a href="https://cran.r-project.org/package=patchwork">patchwork</a></span> puts it together.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Row 1</span></span>
<span><span class="op">(</span> <span class="va">delivery_dist</span> <span class="op">+</span> <span class="va">delivery_time</span> <span class="op">)</span> <span class="op">/</span> </span>
<span>  <span class="co"># Row 2</span></span>
<span>  <span class="op">(</span> <span class="va">delivery_day</span> <span class="op">+</span> <span class="va">delivery_time_day</span> <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Consolidate the legends</span></span>
<span>  <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_layout.html">plot_layout</a></span><span class="op">(</span>guides <span class="op">=</span> <span class="st">'collect'</span><span class="op">)</span>  <span class="op">&amp;</span> </span>
<span>  <span class="co"># Place the legend at the bottom</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>legend.title <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>, legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></span>
<span><span class="co">#&gt; `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</span></span>
<span><span class="co">#&gt; `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</span></span>
<span><span class="co">#&gt; `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/delivery-predictors-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><span class="pkg"><a href="https://cran.r-project.org/package=ggplot2">ggplot2</a></span> is a bit noisy. The messages tell you details about how it made the smooth trend line. The code <code>s(x, bs = "cs")</code> defines a <em>spline smoother</em> that we will see more of shortly (using a different function).</p>
<p>The methods that we used to compute the effects of the <code>item_*</code> columns are more complicated. We must make probabilistic assumptions about the data if we want to get something like a confidence interval. Alternatively, we could specify the empirical distribution function via the bootstrap resampling method. This helps us estimate the standard error of some statistic and use that to compute an interval.</p>
<p>First, we make a function that takes some data and <a href="https://rsample.tidymodels.org/reference/int_pctl.html#arguments">computes our statistics of interest</a>. It assumes <code>x</code> is the entire data set with the delivery time column and each item column.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">time_ratios</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">x</span> <span class="op">%&gt;%</span></span>
<span>    <span class="co"># The items are in columns; we'll stack these columns on one another.</span></span>
<span>    <span class="fu">pivot_longer</span><span class="op">(</span></span>
<span>      cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu">starts_with</span><span class="op">(</span><span class="st">"item"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>      names_to <span class="op">=</span> <span class="st">"predictor"</span>,</span>
<span>      values_to <span class="op">=</span> <span class="st">"count"</span></span>
<span>    <span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="co"># Collapse the counts into a "in order"/"not in order" variable. </span></span>
<span>    <span class="fu">mutate</span><span class="op">(</span>ordered <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">count</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="st">"yes"</span>, <span class="st">"no"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="co"># Compute, for each value of the 'predictor' and 'ordered' columns, </span></span>
<span>    <span class="co"># the mean delivery time. </span></span>
<span>    <span class="fu">summarize</span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">time_to_delivery</span><span class="op">)</span>,</span>
<span>              .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">predictor</span>, <span class="va">ordered</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="co"># Move the means to columns for when they were in the order </span></span>
<span>    <span class="co"># and when they were not. The new column names are `yes` and `no`.</span></span>
<span>    <span class="fu">pivot_wider</span><span class="op">(</span>id_cols <span class="op">=</span> <span class="va">predictor</span>,</span>
<span>                names_from <span class="op">=</span> <span class="va">ordered</span>,</span>
<span>                values_from <span class="op">=</span> <span class="va">mean</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="co"># Compute the ratio. This is a fold-difference in delivery times.</span></span>
<span>    <span class="fu">mutate</span><span class="op">(</span>ratio <span class="op">=</span> <span class="va">yes</span> <span class="op">/</span> <span class="va">no</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>    <span class="fu">select</span><span class="op">(</span>term <span class="op">=</span> <span class="va">predictor</span>, estimate <span class="op">=</span> <span class="va">ratio</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When run in the training set:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">time_ratios</span><span class="op">(</span><span class="va">delivery_train</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 27 × 2</span></span>
<span><span class="co">#&gt;   term    estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 item_01    1.074</span></span>
<span><span class="co">#&gt; 2 item_02    1.010</span></span>
<span><span class="co">#&gt; 3 item_03    1.010</span></span>
<span><span class="co">#&gt; 4 item_04    1.002</span></span>
<span><span class="co">#&gt; 5 item_05    1.005</span></span>
<span><span class="co">#&gt; 6 item_06    1.018</span></span>
<span><span class="co">#&gt; # ℹ 21 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A value of 1.07 means that there is a 7% increase in the delivery time when that item is in the order at least once.</p>
<p>A tidymodels function called <code>int_pctl()</code> can take a collection of bootstrap samples of a data set, compute their statistics, and use the results to produce confidence intervals (we’ll use 90% intervals). To use it, we’ll resample the training set using the <code>bootstraps()</code> function and then use a <code>mutate()</code> to compute the fold differences.</p>
<p>We are using random numbers again, so let’s reset the seed<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">624</span><span class="op">)</span></span>
<span><span class="va">resampled_data</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">delivery_train</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">time_to_delivery</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="st">"item"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="co"># This takes a while to compute. The materials use 5000 bootstraps</span></span>
<span>  <span class="co"># but a smaller number is used here for demonstration.</span></span>
<span>  <span class="fu">bootstraps</span><span class="op">(</span>times <span class="op">=</span> <span class="fl">1001</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">resampled_data</span></span>
<span><span class="co">#&gt; # Bootstrap sampling </span></span>
<span><span class="co">#&gt; # A tibble: 1,001 × 2</span></span>
<span><span class="co">#&gt;   splits              id           </span></span>
<span><span class="co">#&gt;   &lt;list&gt;              &lt;chr&gt;        </span></span>
<span><span class="co">#&gt; 1 &lt;split [6004/2227]&gt; Bootstrap0001</span></span>
<span><span class="co">#&gt; 2 &lt;split [6004/2197]&gt; Bootstrap0002</span></span>
<span><span class="co">#&gt; 3 &lt;split [6004/2156]&gt; Bootstrap0003</span></span>
<span><span class="co">#&gt; 4 &lt;split [6004/2210]&gt; Bootstrap0004</span></span>
<span><span class="co">#&gt; 5 &lt;split [6004/2208]&gt; Bootstrap0005</span></span>
<span><span class="co">#&gt; 6 &lt;split [6004/2227]&gt; Bootstrap0006</span></span>
<span><span class="co">#&gt; # ℹ 995 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>splits</code> column contains the information on each bootstrap sample. To get a specific bootstrap sample, we can use the <code>analysis(split_object)</code> function on each element of the <code>splits</code> column. <code><a href="https://purrr.tidyverse.org/reference/map.html">purrr::map()</a></code> takes each split, extracts the bootstrap sample, then computes all of the ratios<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">resampled_ratios</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">resampled_data</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>stats <span class="op">=</span> <span class="fu">map</span><span class="op">(</span><span class="va">splits</span>, <span class="op">~</span> <span class="fu">time_ratios</span><span class="op">(</span><span class="fu">analysis</span><span class="op">(</span><span class="va">.x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">resampled_ratios</span></span>
<span><span class="co">#&gt; # Bootstrap sampling </span></span>
<span><span class="co">#&gt; # A tibble: 1,001 × 3</span></span>
<span><span class="co">#&gt;   splits              id            stats            </span></span>
<span><span class="co">#&gt;   &lt;list&gt;              &lt;chr&gt;         &lt;list&gt;           </span></span>
<span><span class="co">#&gt; 1 &lt;split [6004/2227]&gt; Bootstrap0001 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; 2 &lt;split [6004/2197]&gt; Bootstrap0002 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; 3 &lt;split [6004/2156]&gt; Bootstrap0003 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; 4 &lt;split [6004/2210]&gt; Bootstrap0004 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; 5 &lt;split [6004/2208]&gt; Bootstrap0005 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; 6 &lt;split [6004/2227]&gt; Bootstrap0006 &lt;tibble [27 × 2]&gt;</span></span>
<span><span class="co">#&gt; # ℹ 995 more rows</span></span>
<span></span>
<span><span class="co"># An example: </span></span>
<span><span class="va">resampled_ratios</span><span class="op">$</span><span class="va">stats</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span></span>
<span><span class="co">#&gt; # A tibble: 27 × 2</span></span>
<span><span class="co">#&gt;   term    estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 item_01    1.070</span></span>
<span><span class="co">#&gt; 2 item_02    1.018</span></span>
<span><span class="co">#&gt; 3 item_03    1.008</span></span>
<span><span class="co">#&gt; 4 item_04    1.008</span></span>
<span><span class="co">#&gt; 5 item_05    1.017</span></span>
<span><span class="co">#&gt; 6 item_06    1.007</span></span>
<span><span class="co">#&gt; # ℹ 21 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://rsample.tidymodels.org/reference/int_pctl.html">rsample::int_pctl()</a></code> can consume these results and produce an interval for each item column<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">resampled_intervals</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">resampled_ratios</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">int_pctl</span><span class="op">(</span><span class="va">stats</span>, alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">resampled_intervals</span></span>
<span><span class="co">#&gt; # A tibble: 27 × 6</span></span>
<span><span class="co">#&gt;   term    .lower .estimate .upper .alpha .method   </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;     </span></span>
<span><span class="co">#&gt; 1 item_01 1.052      1.075  1.097    0.1 percentile</span></span>
<span><span class="co">#&gt; 2 item_02 0.9950     1.009  1.024    0.1 percentile</span></span>
<span><span class="co">#&gt; 3 item_03 0.9940     1.009  1.024    0.1 percentile</span></span>
<span><span class="co">#&gt; 4 item_04 0.9879     1.002  1.016    0.1 percentile</span></span>
<span><span class="co">#&gt; 5 item_05 0.9884     1.005  1.021    0.1 percentile</span></span>
<span><span class="co">#&gt; 6 item_06 1.002      1.018  1.033    0.1 percentile</span></span>
<span><span class="co">#&gt; # ℹ 21 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here’s our plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">resampled_intervals</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="co"># Convert the folds to percentages and make the item values</span></span>
<span>  <span class="co"># a little cleaner:</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    term <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"_0"</span>, <span class="st">" "</span>, <span class="va">term</span><span class="op">)</span>,</span>
<span>    term <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">gsub</a></span><span class="op">(</span><span class="st">"_"</span>, <span class="st">" "</span>, <span class="va">term</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    term <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">term</span>, <span class="va">.estimate</span><span class="op">)</span>,</span>
<span>    increase <span class="op">=</span> <span class="va">.estimate</span> <span class="op">-</span> <span class="fl">1</span>,</span>
<span>  <span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">increase</span>, <span class="va">term</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0</span>, col <span class="op">=</span> <span class="st">"red"</span>, alpha <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_errorbar</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">.lower</span> <span class="op">-</span> <span class="fl">1</span>, xmax <span class="op">=</span> <span class="va">.upper</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>, width <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="va"><a href="https://scales.r-lib.org/reference/percent_format.html">percent</a></span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="cn">NULL</span>, x <span class="op">=</span> <span class="st">"Increase in Delivery Time When Ordered"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">theme</span><span class="op">(</span>axis.text.y <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>hjust <span class="op">=</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/time-ratio-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="model-development" class="level2" data-number="2.5"><h2 data-number="2.5" class="anchored" data-anchor-id="model-development">
<span class="header-section-number">2.5</span> Model Development</h2>
<p>The analyses in this section define a model pipeline, fit it to the training set, and then measure performance using the validation set. We’ll review the three evaluated models and describe how those computations were done.</p>
<p>Before we get started, we need to specify how to measure model effectiveness. The materials use the mean absolute error (MAE). To specify this <em>performance metric</em>, you can use the <code><a href="https://yardstick.tidymodels.org/reference/metric_set.html">yardstick::metric_set()</a></code> function and give it the function names for specific metrics (like the <code><a href="https://yardstick.tidymodels.org/reference/mae.html">yardstick::mae()</a></code> function):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg_metrics</span> <span class="op">&lt;-</span> <span class="fu">metric_set</span><span class="op">(</span><span class="va">mae</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll show you how to use <code>reg_metrics</code> in a bit.</p>
<section id="linear-regression" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="linear-regression">Linear Regression</h3>
<p>The linear regression model is fairly simple to define and fit. Before we get to that, we must introduce a major tidymodels component: <strong>the recipe</strong>.</p>
<p>A recipe is a set of instructions defining a potential series of computations on the predictor variables to put them into a format the model (or data set) requires. For example, the day-of-the-week factor must be converted into a numeric format. We’ll use the standard “Dummy variable” approach to do that. Additionally, our exploratory data analysis discovered that:</p>
<ul>
<li>There is a nonlinear relationship between the outcome and the time of the order.</li>
<li>This nonlinear relationship is different for different days. This is an interaction effect between a qualitative predictor (<code>day</code>) and a nonlinear function of another (<code>hour</code>).</li>
<li>There also appeared to be an additional nonlinear effect for the order distance.</li>
</ul>
<p>We can initialize a recipe using a simple formula method:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spline_rec</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are a few things that this function call does:</p>
<ul>
<li>The formula declares that the column <code>time_to_delivery</code> is the outcome (since it is on the left-hand side of the tilde). The dot on the right-hand side indicates that all of the columns in <code>delivery_train</code>, besides the outcome, should be treated as predictors.</li>
<li>The recipe collects information on each column’s <em>type</em>. For example, it understands that <code>day</code> is a factor and that the <code>item_*</code> columns are numeric.</li>
</ul>
<p>Let’s add to the recipe by converting <code>day</code> to indicator columns. We do this by adding a step to the recipe via:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spline_rec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_factor_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument to step functions is the variables that should be affected by the function. We can use any <span class="pkg"><a href="https://cran.r-project.org/package=dplyr">dplyr</a></span> <a href="https://dplyr.tidyverse.org/reference/select.html">selector</a> such as <code>everything()</code> and/or the bare column names. Here, we want to change every factor column that was the role of “predictor”. For this purpose, recipes have an <a href="https://recipes.tidymodels.org/reference/selections.html">extended set of selector functions</a>.</p>
<p>Once the recipe is processed, this step will record which columns were captured by <code>all_factor_predictors()</code>, retain their factor levels, then convert them to a set of 0/1 indicators for each predictor/level.</p>
<p>Unlike base R’s formula method, the resulting columns are named rationally. By default, it uses the pattern <code>{column name}_{level}</code> for the new features. So, the column <code>day</code> will not exist after this step. It is replaced with columns such as <code>day_Thursday</code> and so on.</p>
<p>The next recipe step is probably unnecessary for this data set but automatically using it is not problematic. What happens if there is a factor level that occurs very infrequently? It is possible that this will only be observed in the validation or test set. <code>step_dummy()</code> will make a column for that factor level since it knows it exists but the training set will have all zeros for this column; it has zero variance. We can screen these out using <code>step_zv()</code> (‘zv’ = zero-variance):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spline_rec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_factor_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can address the nonlinear effects. We’ll use a spline basis expansion (described later on the main page) that creates additional columns from some numeric predictor. We’ll use a <em>natural spline</em> function and create ten new columns for both <code>hour</code> and <code>distance</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spline_rec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_factor_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_spline_natural</span><span class="op">(</span><span class="va">hour</span>, <span class="va">distance</span>, deg_free <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The naming convention for these new features are <code>hour_01</code> … <code>hour_10</code> and so on. The original <code>hour</code> column is removed (same for the <code>distance</code> column).</p>
<p>This step allows the linear regression to have nonlinear relationships between predictors and the outcome.</p>
<p>Finally, we can create interactions. In base R, an interaction between variables <code>a</code> and <code>b</code> is specified in the formula using <code>a:b</code>. We’ll use the same method here with <code>step_interact()</code>. The main difference is that the columns <code>day</code> and <code>hour</code> no longer exist at this point. To capture all of the interactions, we can use the <code>:</code> convention with selector functions. Using <code>starts_wth("day_")</code> will capture the existing indicator columns and, similarly, <code>starts_wth("hour_")</code> finds the appropriate spline terms. Our final recipe is then:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">spline_rec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_factor_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_spline_natural</span><span class="op">(</span><span class="va">hour</span>, <span class="va">distance</span>, deg_free <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">step_interact</span><span class="op">(</span><span class="op">~</span> <span class="fu">starts_with</span><span class="op">(</span><span class="st">"hour_"</span><span class="op">)</span><span class="op">:</span><span class="fu">starts_with</span><span class="op">(</span><span class="st">"day_"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learn More About Recipes
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can learn more about recipes later and there is material in the tidymodels book as well as <code>tidymodels.org</code>.</p>
<ul>
<li><a href="https://www.tmwr.org/recipes"><em>Feature Engineering with recipes</em></a></li>
<li><a href="https://www.tmwr.org/dimensionality"><em>Dimensionality Reduction</em></a></li>
<li><a href="https://www.tmwr.org/categorical"><em>Encoding Categorical Data</em></a></li>
<li><a href="https://www.tidymodels.org/start/recipes/"><em>Get Started: Preprocess your data with recipes</em></a></li>
<li><a href="https://www.tidymodels.org/learn/#category=recipes">Articles with recipes</a></li>
<li><a href="https://www.tidymodels.org/find/recipes/">A list of recipe steps on CRAN</a></li>
</ul>
</div>
</div>
<p>To specify the linear regression model, we use one of the functions from the <span class="pkg"><a href="https://cran.r-project.org/package=parsnip">parsnip</a></span> package called… <code><a href="https://parsnip.tidymodels.org/reference/linear_reg.html">linear_reg()</a></code>. Since we are using ordinary least squares, this function defaults to <code>stats::lm().</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># This creates a model specification: </span></span>
<span><span class="va">lm_spec</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">lm_spec</span></span>
<span><span class="co">#&gt; Linear Regression Model Specification (regression)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Computational engine: lm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <em>engine</em> mentioned here is the computational method to fit the model. R has many ways to do this and <code>"lm"</code> is the <em>default engine</em>.</p>
<p>How do we combine the recipe and the model specifications? The best approach is to make a pipeline-like object called a <em>workflow</em>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_wflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_model</span><span class="op">(</span><span class="va">lm_spec</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">spline_rec</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can use the <code><a href="https://generics.r-lib.org/reference/fit.html">fit()</a></code> function to fit the workflow to the training set. This executes the recipe on the data set then passes the appropriate data to <code><a href="https://rdrr.io/r/stats/lm.html">stats::lm()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="va">lin_reg_wflow</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can print the results out but the results are kind of long:</p>
<details><div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_fit</span></span>
<span><span class="co">#&gt; ══ Workflow [trained] ═══════════════════════════════════════════════════════════════</span></span>
<span><span class="co">#&gt; Preprocessor: Recipe</span></span>
<span><span class="co">#&gt; Model: linear_reg()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Preprocessor ─────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; 4 Recipe Steps</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; • step_dummy()</span></span>
<span><span class="co">#&gt; • step_zv()</span></span>
<span><span class="co">#&gt; • step_spline_natural()</span></span>
<span><span class="co">#&gt; • step_interact()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Model ────────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; stats::lm(formula = ..y ~ ., data = data)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;       (Intercept)            item_01            item_02            item_03  </span></span>
<span><span class="co">#&gt;           13.3434             1.2444             0.6461             0.7313  </span></span>
<span><span class="co">#&gt;           item_04            item_05            item_06            item_07  </span></span>
<span><span class="co">#&gt;            0.2820             0.5839             0.5250             0.5063  </span></span>
<span><span class="co">#&gt;           item_08            item_09            item_10            item_11  </span></span>
<span><span class="co">#&gt;            0.6376             0.7368             1.5341             0.5172  </span></span>
<span><span class="co">#&gt;           item_12            item_13            item_14            item_15  </span></span>
<span><span class="co">#&gt;            0.5945             0.5799             0.5080             0.6432  </span></span>
<span><span class="co">#&gt;           item_16            item_17            item_18            item_19  </span></span>
<span><span class="co">#&gt;            0.4309             0.6089             0.4028            -0.3568  </span></span>
<span><span class="co">#&gt;           item_20            item_21            item_22            item_23  </span></span>
<span><span class="co">#&gt;            0.5280             0.7743             0.5105             0.6876  </span></span>
<span><span class="co">#&gt;           item_24            item_25            item_26            item_27  </span></span>
<span><span class="co">#&gt;            0.8126             0.4768             0.5274             0.5773  </span></span>
<span><span class="co">#&gt;           day_Tue            day_Wed            day_Thu            day_Fri  </span></span>
<span><span class="co">#&gt;           -1.1200            -2.8421            -3.7059            -4.3130  </span></span>
<span><span class="co">#&gt;           day_Sat            day_Sun            hour_01            hour_02  </span></span>
<span><span class="co">#&gt;           -4.6659            -3.0919             1.8776             2.5588  </span></span>
<span><span class="co">#&gt;           hour_03            hour_04            hour_05            hour_06  </span></span>
<span><span class="co">#&gt;            2.5826             3.8464             2.5826             4.0220  </span></span>
<span><span class="co">#&gt;           hour_07            hour_08            hour_09            hour_10  </span></span>
<span><span class="co">#&gt;            4.0112             5.9056            -0.8782            11.1905  </span></span>
<span><span class="co">#&gt;       distance_01        distance_02        distance_03        distance_04  </span></span>
<span><span class="co">#&gt;           -0.0523             0.5777             0.6157             0.7524  </span></span>
<span><span class="co">#&gt;       distance_05        distance_06        distance_07        distance_08  </span></span>
<span><span class="co">#&gt;            1.6695             1.7837             2.9039             3.3200  </span></span>
<span><span class="co">#&gt;       distance_09        distance_10  hour_01_x_day_Tue  hour_01_x_day_Wed  </span></span>
<span><span class="co">#&gt;          -19.3835            75.2868             1.3304             1.2875  </span></span>
<span><span class="co">#&gt; hour_01_x_day_Thu  hour_01_x_day_Fri  hour_01_x_day_Sat  hour_01_x_day_Sun  </span></span>
<span><span class="co">#&gt;            2.4448             1.3560             2.4253             1.5058  </span></span>
<span><span class="co">#&gt; hour_02_x_day_Tue  hour_02_x_day_Wed  hour_02_x_day_Thu  hour_02_x_day_Fri  </span></span>
<span><span class="co">#&gt;            0.2268             3.1441             3.9958             4.8608  </span></span>
<span><span class="co">#&gt; hour_02_x_day_Sat  hour_02_x_day_Sun  hour_03_x_day_Tue  hour_03_x_day_Wed  </span></span>
<span><span class="co">#&gt;            4.8380             3.7002             2.9359             6.4783  </span></span>
<span><span class="co">#&gt; hour_03_x_day_Thu  hour_03_x_day_Fri  hour_03_x_day_Sat  hour_03_x_day_Sun  </span></span>
<span><span class="co">#&gt;            7.4590             9.9423            10.9673             5.7549  </span></span>
<span><span class="co">#&gt; hour_04_x_day_Tue  hour_04_x_day_Wed  hour_04_x_day_Thu  hour_04_x_day_Fri  </span></span>
<span><span class="co">#&gt;            1.6701             6.2609             9.7183            12.1586  </span></span>
<span><span class="co">#&gt; hour_04_x_day_Sat  hour_04_x_day_Sun  hour_05_x_day_Tue  hour_05_x_day_Wed  </span></span>
<span><span class="co">#&gt;           13.9715             7.9502             3.9981             9.4129  </span></span>
<span><span class="co">#&gt; hour_05_x_day_Thu  hour_05_x_day_Fri  hour_05_x_day_Sat  hour_05_x_day_Sun  </span></span>
<span><span class="co">#&gt;           12.1748            16.5402            17.5038             9.3518  </span></span>
<span><span class="co">#&gt; hour_06_x_day_Tue  hour_06_x_day_Wed  hour_06_x_day_Thu  hour_06_x_day_Fri  </span></span>
<span><span class="co">#&gt;            2.5202             8.2079            11.9678            15.7150  </span></span>
<span><span class="co">#&gt; hour_06_x_day_Sat  hour_06_x_day_Sun  hour_07_x_day_Tue  hour_07_x_day_Wed  </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ...</span></span>
<span><span class="co">#&gt; and 14 more lines.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</details><p>One helpful function is <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code>. It is designed to return the object results rationally, helpfully. In our case, the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> method for an <code>lm</code> object gives us a nice data frame back with information on the fitted coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tidy</span><span class="op">(</span><span class="va">lin_reg_fit</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 114 × 5</span></span>
<span><span class="co">#&gt;   term        estimate std.error statistic   p.value</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 (Intercept)  13.34     1.585       8.420 4.664e-17</span></span>
<span><span class="co">#&gt; 2 item_01       1.244    0.1031     12.08  3.498e-33</span></span>
<span><span class="co">#&gt; 3 item_02       0.6461   0.06865     9.412 6.852e-21</span></span>
<span><span class="co">#&gt; 4 item_03       0.7313   0.06914    10.58  6.463e-26</span></span>
<span><span class="co">#&gt; 5 item_04       0.2820   0.06260     4.505 6.776e- 6</span></span>
<span><span class="co">#&gt; 6 item_05       0.5839   0.07871     7.418 1.360e-13</span></span>
<span><span class="co">#&gt; # ℹ 108 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unlike the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> method for <code>lm</code> objects, this object can immediately be used in plots or tables.</p>
<p>Another valuable supporting function is <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>. It can take a model object and data set and attach the prediction columns to the data frame. Essentially, this is an upgraded version of <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>. Let’s predict the validation set:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_reg_val_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">lin_reg_fit</span>, new_data <span class="op">=</span> <span class="va">delivery_val</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">lm_reg_val_pred</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] ".pred"            ".resid"           "time_to_delivery" "hour"            </span></span>
<span><span class="co">#&gt;  [5] "day"              "distance"         "item_01"          "item_02"         </span></span>
<span><span class="co">#&gt;  [9] "item_03"          "item_04"          "item_05"          "item_06"         </span></span>
<span><span class="co">#&gt; [13] "item_07"          "item_08"          "item_09"          "item_10"         </span></span>
<span><span class="co">#&gt; [17] "item_11"          "item_12"          "item_13"          "item_14"         </span></span>
<span><span class="co">#&gt; [21] "item_15"          "item_16"          "item_17"          "item_18"         </span></span>
<span><span class="co">#&gt; [25] "item_19"          "item_20"          "item_21"          "item_22"         </span></span>
<span><span class="co">#&gt; [29] "item_23"          "item_24"          "item_25"          "item_26"         </span></span>
<span><span class="co">#&gt; [33] "item_27"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What is our MAE? This is where we use our metric set <code>reg_metrics</code>. Note that there is a column in the results called <code>.pred</code>. For regression models, this is the predicted delivery time for each order in the validation set. We can use that and the original observed outcome column to estimate the MAE<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_reg_val_pred</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">reg_metrics</span><span class="op">(</span>truth <span class="op">=</span> <span class="va">time_to_delivery</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;   .metric .estimator .estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mae     standard       1.609</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The units are fractional minutes.</p>
<p>At this point, we can make diagnostic plots of our data and so on.</p>
<p>Let’s take a minor distraction that will pay off a bit later. The main page mentions that we can treat the validation set as a single resample of the data. If we were to do that, our code wouldn’t have to change much when we get into more complex scenarios such as cross-validation or model tuning. To do this, we can convert the initial split object into a resampling set (a.k.a. an <code>rset</code>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">delivery_rs</span> <span class="op">&lt;-</span> <span class="fu">validation_set</span><span class="op">(</span><span class="va">delivery_split</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">delivery_rs</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "validation_set" "rset"           "tbl_df"         "tbl"           </span></span>
<span><span class="co">#&gt; [5] "data.frame"</span></span>
<span></span>
<span><span class="va">delivery_rs</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 2</span></span>
<span><span class="co">#&gt;   splits              id        </span></span>
<span><span class="co">#&gt;   &lt;list&gt;              &lt;chr&gt;     </span></span>
<span><span class="co">#&gt; 1 &lt;split [6004/2004]&gt; validation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This packages the training and validation sets together in a way that it knows when to use each data set appropriately.</p>
<p>Since we are treating this as if it were resampling, we can use the <code>fit_resamples()</code> function to do much of the manual work we just showed. We’ll add a <em>control object</em> to the mix to specify that we want to retain the validation set predictions (and our original workflow).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ctrl_rs</span> <span class="op">&lt;-</span> <span class="fu">control_resamples</span><span class="op">(</span>save_pred <span class="op">=</span> <span class="cn">TRUE</span>, save_workflow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">lin_reg_res</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">fit_resamples</span><span class="op">(</span><span class="va">lin_reg_wflow</span>,</span>
<span>                resamples <span class="op">=</span> <span class="va">delivery_rs</span>,</span>
<span>                control <span class="op">=</span> <span class="va">ctrl_rs</span>,</span>
<span>                metrics <span class="op">=</span> <span class="va">reg_metrics</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The benefit here is that there are a lot of <em>helper</em> functions to simplify your code. For example, to get the validation set MAE and predictions:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="va">lin_reg_res</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 6</span></span>
<span><span class="co">#&gt;   .metric .estimator  mean     n std_err .config             </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 mae     standard   1.609     1      NA Preprocessor1_Model1</span></span>
<span></span>
<span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span><span class="va">lin_reg_res</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2,004 × 5</span></span>
<span><span class="co">#&gt;   .pred id          .row time_to_delivery .config             </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;int&gt;            &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 30.12 validation  6005            27.23 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 2 23.02 validation  6006            22.10 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 3 28.38 validation  6007            26.63 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 4 31.04 validation  6008            30.84 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 5 38.57 validation  6009            41.17 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 6 27.04 validation  6010            27.04 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; # ℹ 1,998 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <span class="pkg"><a href="https://cran.r-project.org/package=probably">probably</a></span> package also has a nice helper to check the calibration of the model via a plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">cal_plot_regression</a></span><span class="op">(</span><span class="va">lin_reg_res</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/lm-cal-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="rule-based-ensemble" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="rule-based-ensemble">Rule-Based Ensemble</h3>
<p>To fit the Cubist model, we need to load one of the tidymodels <em>extension packages</em> called <span class="pkg"><a href="https://cran.r-project.org/package=rules">rules</a></span>. It has the tools to fit this model and will automatically (and silently) use the <span class="pkg"><a href="https://cran.r-project.org/package=Cubist">Cubist</a></span> package when the model fit occurs.</p>
<p>We’ll create a model specification that has an enselmble size of 100:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/rules">rules</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># A model specification: </span></span>
<span><span class="va">cb_spec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://parsnip.tidymodels.org/reference/cubist_rules.html">cubist_rules</a></span><span class="op">(</span>committees <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>One advantage of rule-based models is that very little preprocessing is required (i.e., no dummy variables or spline terms). For that reason, we’ll use a simple R formula instead of a recipe:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cb_wflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">add_model</span><span class="op">(</span><span class="va">cb_spec</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">add_formula</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s go straight to <code>fit_resamples()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cb_res</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">fit_resamples</span><span class="op">(</span></span>
<span>    <span class="va">cb_wflow</span>, </span>
<span>    resamples <span class="op">=</span> <span class="va">delivery_rs</span>, </span>
<span>    control <span class="op">=</span> <span class="va">ctrl_rs</span>, </span>
<span>    metrics <span class="op">=</span> <span class="va">reg_metrics</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="va">cb_res</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 6</span></span>
<span><span class="co">#&gt;   .metric .estimator  mean     n std_err .config             </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 mae     standard   1.416     1      NA Preprocessor1_Model1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The calibration plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">cal_plot_regression</a></span><span class="op">(</span><span class="va">cb_res</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/cb-cal-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>This is pretty simple and demonstrates that, after an initial investment in learning tidymodels syntax, the process of fitting different models does not require huge changes to your scripts.</p>
<p>To get the model fit, we previously used <code><a href="https://generics.r-lib.org/reference/fit.html">fit()</a></code>. With resampling objects (and the tuning objects that we are about to see), there is another helper function called <code>fit_best()</code> that will create the model from the entire training set using the resampling results<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cb_fit</span> <span class="op">&lt;-</span> <span class="fu">fit_best</span><span class="op">(</span><span class="va">cb_res</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cb_fit</span></span>
<span><span class="co">#&gt; ══ Workflow [trained] ═══════════════════════════════════════════════════════════════</span></span>
<span><span class="co">#&gt; Preprocessor: Formula</span></span>
<span><span class="co">#&gt; Model: cubist_rules()</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Preprocessor ─────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; time_to_delivery ~ .</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Model ────────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; cubist.default(x = x, y = y, committees = 100)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of samples: 6004 </span></span>
<span><span class="co">#&gt; Number of predictors: 30 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of committees: 100 </span></span>
<span><span class="co">#&gt; Number of rules per committee: 31, 22, 23, 26, 21, 24, 23, 23, 22, 23, 21, 22, 18, 24, 20, 22, 16, 26, 25, 26 ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> method is also helpful here. It contains all of the rules and corresponding regression models. Let’s get these values for the second rule in the fourth ensemble:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rule_details</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">cb_fit</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rule_details</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">committee</span> <span class="op">==</span> <span class="fl">4</span> <span class="op">&amp;</span> <span class="va">rule_num</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="st">"rule"</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "( hour &lt;= 14.946 ) &amp; ( day  %in% c( 'Mon','Tue','Wed','Thu','Sun' ) ) &amp; ( distance &lt;= 4.52 )"</span></span>
<span></span>
<span><span class="va">rule_details</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">committee</span> <span class="op">==</span> <span class="fl">4</span> <span class="op">&amp;</span> <span class="va">rule_num</span> <span class="op">==</span> <span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">estimate</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="fl">1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">pluck</span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 15 × 2</span></span>
<span><span class="co">#&gt;   term        estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;          &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 (Intercept)   -11.24</span></span>
<span><span class="co">#&gt; 2 hour            2.05</span></span>
<span><span class="co">#&gt; 3 distance        0.78</span></span>
<span><span class="co">#&gt; 4 item_01        -0.5 </span></span>
<span><span class="co">#&gt; 5 item_02         0.3 </span></span>
<span><span class="co">#&gt; 6 item_05         0.8 </span></span>
<span><span class="co">#&gt; # ℹ 9 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="neural-network" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="neural-network">Neural Network</h3>
<p>The model function for this type of model is <code><a href="https://parsnip.tidymodels.org/reference/mlp.html">parsnip::mlp()</a></code> (MLP is short for “multi-layer perceptron”). There are quite a few packages for neural networks in R. tidymodels has interfaces to several engines:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://parsnip.tidymodels.org/reference/show_engines.html">show_engines</a></span><span class="op">(</span><span class="st">"mlp"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 2</span></span>
<span><span class="co">#&gt;   engine mode          </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;chr&gt;         </span></span>
<span><span class="co">#&gt; 1 keras  classification</span></span>
<span><span class="co">#&gt; 2 keras  regression    </span></span>
<span><span class="co">#&gt; 3 nnet   classification</span></span>
<span><span class="co">#&gt; 4 nnet   regression    </span></span>
<span><span class="co">#&gt; 5 brulee classification</span></span>
<span><span class="co">#&gt; 6 brulee regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll use the <span class="pkg"><a href="https://cran.r-project.org/package=brulee">brulee</a></span> package. This uses the <code>torch</code> software to fit the model. We’ll only tune the number of hidden units (for now, see later chapters). To mark <em>any</em> parameter for tuning, we pass the <code><a href="https://hardhat.tidymodels.org/reference/tune.html">tune()</a></code> function to an argument:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nnet_spec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/mlp.html">mlp</a></span><span class="op">(</span></span>
<span>    hidden_units <span class="op">=</span> <span class="fu"><a href="https://hardhat.tidymodels.org/reference/tune.html">tune</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    <span class="co"># Some specific argument values that we chose:</span></span>
<span>    penalty <span class="op">=</span> <span class="fl">0.01</span>,</span>
<span>    learn_rate <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>    epochs <span class="op">=</span> <span class="fl">5000</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_args.html">set_mode</a></span><span class="op">(</span><span class="st">"regression"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://parsnip.tidymodels.org/reference/set_engine.html">set_engine</a></span><span class="op">(</span><span class="st">"brulee"</span>, stop_iter <span class="op">=</span> <span class="fl">10</span>, rate_schedule <span class="op">=</span> <span class="st">"cyclic"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A few notes on this:</p>
<ul>
<li>The arguments to <code><a href="https://parsnip.tidymodels.org/reference/mlp.html">mlp()</a></code> are called the <em>main arguments</em> since they are used by several engines.</li>
<li>The default engine uses the <span class="pkg"><a href="https://cran.r-project.org/package=nnet">nnet</a></span> package; <code><a href="https://parsnip.tidymodels.org/reference/set_engine.html">set_engine()</a></code> specifies that we want to use the <span class="pkg"><a href="https://cran.r-project.org/package=brulee">brulee</a></span> package instead.</li>
<li>Two arguments (<code>stop_iter</code> and <code>rate_schedule</code>) are specific to our engine. We set them here (and can also pass a <code><a href="https://hardhat.tidymodels.org/reference/tune.html">tune()</a></code> value to them).</li>
<li>Neural networks can fit both classification and regression models. We must state what model type (called a “mode”) to create.</li>
</ul>
<p>This model requires the conversion to dummy variables but does not require features to handle nonlinear trends and interactions. One additional preprocessing step that is required is to put the predictors in the same units (e.g., not miles or hours). There are a few ways to do this. We will center and scale the predictors using <code><a href="https://recipes.tidymodels.org/reference/step_normalize.html">recipes::step_normalize()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">norm_rec</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">recipe</span><span class="op">(</span><span class="va">time_to_delivery</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_factor_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">step_normalize</span><span class="op">(</span><span class="fu">all_numeric_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">nnet_wflow</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">add_model</span><span class="op">(</span><span class="va">nnet_spec</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">norm_rec</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unlike the previous models, we are tuning one of the hyper-parameters. Instead of <code>fit_resamples()</code>, we’ll use <code>tune_grid()</code> to search over a predefined set of values for the number of hidden units. We can set <em>how many</em> values we should try or directly declare the candidate values. We’ll do the latter and, for simplicity, use a smaller range of values.</p>
<p>Finally, we’ll use another control function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The main materials used 2:100</span></span>
<span><span class="va">nnet_grid</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>hidden_units <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ctrl_grid</span> <span class="op">&lt;-</span> <span class="fu">control_grid</span><span class="op">(</span>save_pred <span class="op">=</span> <span class="cn">TRUE</span>, save_workflow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The model initializes the parameters with random numbers so set the seed:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">388</span><span class="op">)</span></span>
<span><span class="va">nnet_res</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">tune_grid</span><span class="op">(</span><span class="va">nnet_wflow</span>,</span>
<span>            resamples <span class="op">=</span> <span class="va">delivery_rs</span>,</span>
<span>            control <span class="op">=</span> <span class="va">ctrl_grid</span>,</span>
<span>            grid <span class="op">=</span> <span class="va">nnet_grid</span>,</span>
<span>            metrics <span class="op">=</span> <span class="va">reg_metrics</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are some additional helper functions for model tuning. For example, we can rank the models based on a metric:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">show_best</span><span class="op">(</span><span class="va">nnet_res</span>, metric <span class="op">=</span> <span class="st">"mae"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 7</span></span>
<span><span class="co">#&gt;   hidden_units .metric .estimator  mean     n std_err .config             </span></span>
<span><span class="co">#&gt;          &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1            5 mae     standard   1.497     1      NA Preprocessor1_Model4</span></span>
<span><span class="co">#&gt; 2            9 mae     standard   1.511     1      NA Preprocessor1_Model8</span></span>
<span><span class="co">#&gt; 3            7 mae     standard   1.519     1      NA Preprocessor1_Model6</span></span>
<span><span class="co">#&gt; 4           10 mae     standard   1.525     1      NA Preprocessor1_Model9</span></span>
<span><span class="co">#&gt; 5            8 mae     standard   1.603     1      NA Preprocessor1_Model7</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also return the parameter with the numerically best results<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">best_hidden_units</span> <span class="op">&lt;-</span> <span class="fu">select_best</span><span class="op">(</span><span class="va">nnet_res</span>, metric <span class="op">=</span> <span class="st">"mae"</span><span class="op">)</span></span>
<span><span class="va">best_hidden_units</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 2</span></span>
<span><span class="co">#&gt;   hidden_units .config             </span></span>
<span><span class="co">#&gt;          &lt;int&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1            5 Preprocessor1_Model4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot()</a></code> method can visualize the relationship between the tuning parameter(s) and the performance metric(s).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">nnet_res</span>, metric <span class="op">=</span> <span class="st">"mae"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/nnet-autoplot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><code><a href="https://tune.tidymodels.org/reference/collect_predictions.html">tune::collect_predictions()</a></code> will automatically return the out-of-sample predictions for every candidate model (e.g., every tuning parameter value.). We might not want them all; it has an argument called <code>parameters</code> that can be used to filter the results.</p>
<p><code><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">probably::cal_plot_regression()</a></code> automatically shows the results for each tuning parameter combination. For example:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">cal_plot_regression</a></span><span class="op">(</span><span class="va">nnet_res</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/nnet-cal-plot-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>There are two options if we need a model fit on the training set. If the numerically best parameter is best (i.e., smallest MAE), then <code><a href="https://tune.tidymodels.org/reference/fit_best.html">tune::fit_best()</a></code> is the easiest approach. Alternatively, you can choose the exact tuning parameter values you desire and <em>splice</em> them into the model to replace the current values of <code><a href="https://hardhat.tidymodels.org/reference/tune.html">tune()</a></code>. To do this, there is a <code>finalize_workflow()</code> function. It takes a data frame with one row and columns for each tuning parameter. Here’s an example where we decide that 10 hidden units are best:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">814</span><span class="op">)</span></span>
<span><span class="va">nnet_fit</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">nnet_wflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">finalize_workflow</span><span class="op">(</span><span class="fu">tibble</span><span class="op">(</span>hidden_units <span class="op">=</span> <span class="fl">10</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">delivery_train</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="aside-parallel-processing" class="level2" data-number="2.6"><h2 data-number="2.6" class="anchored" data-anchor-id="aside-parallel-processing">
<span class="header-section-number">2.6</span> Aside: Parallel Processing</h2>
<p>For model tuning, we are fitting many models. With grid search, these models are not dependent on one another. For this reason, it is possible to compute these model fits simultaneously (i.e., in parallel).</p>
<p>To do so, tidymodels requires you to specify a <em>parallel backend</em>. There are several types, and we will use PSOCK clusters since they work on all operating systems. For this technology, we can run the following commands before running <code>fit_resamples()</code> or any of the <code>tune_*()</code> functions:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cores</span> <span class="op">&lt;-</span> <span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/detectCores.html">detectCores</a></span><span class="op">(</span>logical <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/RevolutionAnalytics/doparallel">doParallel</a></span><span class="op">)</span></span>
<span><span class="va">cl</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/parallel/makeCluster.html">makePSOCKcluster</a></span><span class="op">(</span><span class="va">cores</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/doParallel/man/registerDoParallel.html">registerDoParallel</a></span><span class="op">(</span><span class="va">cl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After we are finished, we also close down the cluster:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">parallel</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/parallel/makeCluster.html">stopCluster</a></span><span class="op">(</span><span class="va">cl</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There can be significant speed-ups when running in parallel. See the <a href="https://www.tmwr.org/grid-search#parallel-processing">section in the tidymodels book</a> for more details.</p>
</section><section id="calibration" class="level2" data-number="2.7"><h2 data-number="2.7" class="anchored" data-anchor-id="calibration">
<span class="header-section-number">2.7</span> Calibration</h2>
<p>The functions to calibrate predictions are in the <span class="pkg"><a href="https://cran.r-project.org/package=probably">probably</a></span> package and have names that start with <code>cal_*</code>. There are methods that work on the results from <code>fit_resamples()</code> or the <code>tune_*()</code> functions, but you can also just use a data frame of predicted values.</p>
<p>We must estimate the trend with the validation set. If we use our object <code>lin_reg_res</code>, it knows what data to use:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_cal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://probably.tidymodels.org/reference/cal_estimate_linear.html">cal_estimate_linear</a></span><span class="op">(</span><span class="va">lin_reg_res</span><span class="op">)</span></span>
<span><span class="va">lin_reg_cal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ── Regression Calibration</span></span>
<span><span class="co">#&gt; Method: Generalized additive model</span></span>
<span><span class="co">#&gt; Source class: Tune Results</span></span>
<span><span class="co">#&gt; Data points: 2,004</span></span>
<span><span class="co">#&gt; Truth variable: `time_to_delivery`</span></span>
<span><span class="co">#&gt; Estimate variable: `.pred`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you’ll see in a minute, the function <code><a href="https://probably.tidymodels.org/reference/cal_apply.html">probably::cal_apply()</a></code> calibrates new predictions.</p>
</section><section id="test-set-results" class="level2" data-number="2.8"><h2 data-number="2.8" class="anchored" data-anchor-id="test-set-results">
<span class="header-section-number">2.8</span> Test Set Results</h2>
<p>As with <code>best_fit()</code>, there are two ways to predict the test set.</p>
<p>The more manual approach is to fit the model on the training set, use <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> or <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> to compute the test set predictions, calibrate them with our object, then use our metric to compute performance. If we had not already fit the model, the pre-calibration code is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/fit.html">fit</a></span><span class="op">(</span><span class="va">lin_reg_wflow</span>, <span class="va">delivery_train</span><span class="op">)</span></span>
<span><span class="va">lin_reg_test_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">lin_reg_fit</span>, <span class="va">delivery_test</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lin_reg_test_pred</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">reg_metrics</span><span class="op">(</span><span class="va">time_to_delivery</span>, <span class="va">.pred</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;   .metric .estimator .estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mae     standard       1.607</span></span>
<span></span>
<span><span class="co"># plot the uncalibrated results: </span></span>
<span><span class="va">lin_reg_test_pred</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">cal_plot_regression</a></span><span class="op">(</span>truth <span class="op">=</span> <span class="va">time_to_delivery</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/lm-test-final-uncal-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>There is a shortcut for the first three commands. <code><a href="https://tune.tidymodels.org/reference/last_fit.html">tune::last_fit()</a></code> takes our initial split object and automatically does the rest (but not calibration yet):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lin_reg_test_res</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lin_reg_wflow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">last_fit</span><span class="op">(</span><span class="va">delivery_split</span>, metrics <span class="op">=</span> <span class="va">reg_metrics</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can pull out the elements we need from this object using some <code>extract_*()</code> and <code>collect_*()</code> functions. Here are a few:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Test set metrics:</span></span>
<span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_metrics</a></span><span class="op">(</span><span class="va">lin_reg_test_res</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 4</span></span>
<span><span class="co">#&gt;   .metric .estimator .estimate .config             </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 mae     standard       1.607 Preprocessor1_Model1</span></span>
<span></span>
<span><span class="co"># Test set predictions: </span></span>
<span><span class="fu"><a href="https://tune.tidymodels.org/reference/collect_predictions.html">collect_predictions</a></span><span class="op">(</span><span class="va">lin_reg_test_res</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2,004 × 5</span></span>
<span><span class="co">#&gt;   .pred id                .row time_to_delivery .config             </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt;            &lt;int&gt;            &lt;dbl&gt; &lt;chr&gt;               </span></span>
<span><span class="co">#&gt; 1 15.98 train/test split     7            18.02 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 2 16.03 train/test split    14            17.57 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 3 27.60 train/test split    16            26.71 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 4 17.15 train/test split    29            17.64 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 5 32.24 train/test split    33            32.19 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; 6 20.18 train/test split    34            20.31 Preprocessor1_Model1</span></span>
<span><span class="co">#&gt; # ℹ 1,998 more rows</span></span>
<span></span>
<span><span class="co"># Final model fit: </span></span>
<span><span class="va">lin_reg_fit</span> <span class="op">&lt;-</span> <span class="fu">extract_fit_parsnip</span><span class="op">(</span><span class="va">lin_reg_test_res</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># cal_plot_regression(lin_reg_test_res)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s calibrate and compute performance:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># apply calibration</span></span>
<span><span class="va">lin_reg_test_pred_cal</span> <span class="op">&lt;-</span> </span>
<span>  <span class="va">lin_reg_test_pred</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://probably.tidymodels.org/reference/cal_apply.html">cal_apply</a></span><span class="op">(</span><span class="va">lin_reg_cal</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lin_reg_test_pred_cal</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">reg_metrics</span><span class="op">(</span><span class="va">time_to_delivery</span>, <span class="va">.pred</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;   .metric .estimator .estimate</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mae     standard       1.545</span></span>
<span></span>
<span><span class="co"># plot the calibrated results: </span></span>
<span><span class="va">lin_reg_test_pred_cal</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://probably.tidymodels.org/reference/cal_plot_regression.html">cal_plot_regression</a></span><span class="op">(</span>truth <span class="op">=</span> <span class="va">time_to_delivery</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="../figures/lm-test-final-cal-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="conclusion" class="level2" data-number="2.9"><h2 data-number="2.9" class="anchored" data-anchor-id="conclusion">
<span class="header-section-number">2.9</span> Conclusion</h2>
<p>This has been an abbreviated, high-level introduction to using tidymodels. Future chapters will go into much more detail on these subjects and illustrate additional features and functions as needed.</p>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>We use a different ggplot theme for the main materials. We’ll use the default theme here.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>If you are wondering how we get the seed values, I use <code>sample.int(1000, 1)</code> to generate random seeds on the fly.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Why are we doing this again? Didn’t we already “jump in the river?” Yes. If we were executing all of the code here in the exact order (with no typos or commands in between), we would have reproducible pseudo-random numbers. That’s usually not how interactive data analysis goes, though. Therefore, we (re)set the seed each time we use randomness.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This <code>map()</code> call can be made much faster by using the <span class="pkg"><a href="https://cran.r-project.org/package=furrr">furrr</a></span> package. It has versions of the <code><a href="https://purrr.tidyverse.org/reference/map.html">purrr::map()</a></code> functions that can run in parallel.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>You can see another example of bootstrap intervals at <a href="https://www.tidymodels.org/learn/statistics/bootstrap/">tidymodels.org</a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>We could have used the <code><a href="https://yardstick.tidymodels.org/reference/mae.html">yardstick::mae()</a></code> directly instead of stuffing that function in a metric set. Since we often want to collect more than one type of performance statistic, we’re showing how to use a metric set.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>This is possible since we previously used the <code>save_workflow = TRUE</code> option in the control function.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>As impressive as the <code>torch</code> ecosystem is, it is not as optimized for reproducibility. These results may vary from run to run due to the inability to fix some of the random numbers used and their use of different numerical tolerances across operating systems.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../chapters/introduction.html" class="pagination-link  aria-label=">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/initial-data-splitting.html" class="pagination-link" aria-label="<span class='chapter-number'>3</span>&nbsp; <span class='chapter-title'>Initial Data Splitting</span>">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Initial Data Splitting</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>